/**
 * Medical condition and medication catalog.
 *
 * Each condition declares the movement attributes that must be excluded,
 * the ones that need caution, an intensity/impact ceiling, mandatory
 * modifications, what to monitor, and the red flags that mean stop.
 * The engine intersects these across every condition the user reports, so
 * the strictest constraint always wins.
 *
 * This encodes widely published exercise-safety guidance (ACSM/WHO/NHS-style
 * pre-participation screening). It is decision support, not a diagnosis, and
 * never replaces the user's own clinician.
 */

import type { ConditionDefinition, MedicationDefinition } from "./types";

export const CONDITIONS: Record<string, ConditionDefinition> = {
  /* ---------------- Musculoskeletal ---------------- */
  osteoarthritis_knee: {
    id: "osteoarthritis_knee",
    label: "Osteoarthritis — knee",
    family: "musculoskeletal",
    avoidTags: ["high_impact", "jumping", "deep_knee_flexion", "rapid_direction_change", "explosive", "contact_risk"],
    cautionTags: ["running_gait", "single_leg", "long_duration"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    maxJointLoad: "moderate",
    preferredCategories: ["swimming", "cycling", "rehab", "mobility", "gym_strength", "walking", "yoga"],
    modifications: [
      "Keep squats and lunges above 90 degrees of knee bend",
      "Use a stationary or recumbent bike with the seat high enough to avoid deep bend",
      "Warm the joint for 10 minutes before any strength work",
      "Prefer water-based cardio on flare days",
    ],
    monitor: ["Pain during and 24 hours after", "Swelling", "Morning stiffness duration"],
    redFlags: ["Sudden severe swelling", "Knee locking or giving way", "Inability to bear weight"],
    clearanceRequired: false,
    suggestedGoals: ["arthritis", "knee_pain", "joint_pain", "weight_loss"],
    note: "Exercise is a first-line treatment for knee OA. Quadriceps and hip strength reduce pain; every kilo lost removes 3-4 kg of knee load per step.",
  },
  osteoarthritis_hip: {
    id: "osteoarthritis_hip",
    label: "Osteoarthritis — hip",
    family: "musculoskeletal",
    avoidTags: ["high_impact", "jumping", "hip_end_range", "rapid_direction_change", "contact_risk"],
    cautionTags: ["running_gait", "single_leg", "deep_knee_flexion"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    maxJointLoad: "moderate",
    preferredCategories: ["swimming", "cycling", "rehab", "mobility", "gym_strength", "walking"],
    modifications: ["Work within pain-free hip range only", "Strengthen glutes in mid-range", "Avoid deep hip flexion and extreme rotation"],
    monitor: ["Groin and lateral hip pain", "Walking distance tolerance"],
    redFlags: ["Night pain at rest", "Sudden inability to weight-bear"],
    clearanceRequired: false,
    suggestedGoals: ["arthritis", "joint_pain", "mobility", "weight_loss"],
    note: "Hip OA responds well to glute strengthening and non-weight-bearing cardio.",
  },
  rheumatoid_arthritis: {
    id: "rheumatoid_arthritis",
    label: "Rheumatoid arthritis",
    family: "immune_oncology",
    avoidTags: ["high_impact", "jumping", "heavy_load", "contact_risk", "hanging_grip", "explosive", "rapid_direction_change"],
    cautionTags: ["wrist_loading", "shoulder_end_range", "long_duration", "deep_knee_flexion"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    maxJointLoad: "low",
    preferredCategories: ["swimming", "mobility", "rehab", "yoga", "walking", "pilates", "breathwork"],
    modifications: [
      "Range-of-motion work daily; reduce range but not frequency during flares",
      "Isometric holds instead of heavy dynamic loading when joints are hot",
      "Avoid gripping heavy dumbbells if hands or wrists are involved — use bands, machines or straps",
      "Warm water is ideal: a heated pool reduces both pain and stiffness",
    ],
    monitor: ["Number of hot swollen joints", "Fatigue", "Morning stiffness duration"],
    redFlags: ["Systemic flare with fever", "Multiple hot swollen joints", "New joint deformity"],
    clearanceRequired: false,
    suggestedGoals: ["arthritis", "joint_pain", "flexibility", "energy_fatigue"],
    note: "Movement does not damage RA joints; deconditioning does. During a systemic flare, drop to gentle range-of-motion only and contact your rheumatologist.",
  },
  osteoporosis: {
    id: "osteoporosis",
    label: "Osteoporosis / osteopenia",
    family: "musculoskeletal",
    avoidTags: ["spinal_flexion", "deep_twist", "sustained_forward_bend", "high_impact", "jumping", "contact_risk", "fall_risk", "inversion"],
    cautionTags: ["loaded_spine", "balance_demand", "heavy_load"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    preferredCategories: ["gym_strength", "walking", "functional", "mobility", "dance"],
    modifications: [
      "No loaded forward bending, crunches or forceful spinal twisting — vertebral fracture risk",
      "Keep the spine neutral in every loaded position",
      "Include weight-bearing work: bone needs load, so swimming alone is not enough",
      "Balance training near support to prevent falls",
    ],
    monitor: ["Any new back pain", "Height loss", "Balance confidence"],
    redFlags: ["Sudden mid-back pain (possible vertebral fracture)", "New spinal deformity"],
    clearanceRequired: false,
    suggestedGoals: ["bone_density", "balance_fall_prevention", "senior_functional", "posture"],
    note: "Progressive resistance training plus balance work is the strongest non-drug intervention for fracture risk.",
  },
  disc_herniation: {
    id: "disc_herniation",
    label: "Disc herniation / sciatica",
    family: "musculoskeletal",
    avoidTags: ["spinal_flexion", "loaded_spine", "deep_twist", "sustained_forward_bend", "high_impact", "jumping", "heavy_load", "intra_abdominal_pressure"],
    cautionTags: ["spinal_extension", "single_leg", "running_gait"],
    intensityCeiling: "light",
    maxImpact: "low",
    maxJointLoad: "low",
    preferredCategories: ["rehab", "walking", "mobility", "swimming", "pilates"],
    modifications: [
      "No loaded or repeated spinal flexion, especially in the morning",
      "Find your directional preference — usually extension-biased movement eases leg symptoms",
      "Walk frequently in short bouts",
      "Brace the trunk and hinge at the hips for every lift",
    ],
    monitor: ["How far down the leg symptoms travel — this should reduce", "Numbness or weakness", "Sitting tolerance"],
    redFlags: [
      "Numbness in the saddle area, or loss of bladder or bowel control — this is an emergency",
      "Progressive leg weakness or foot drop",
    ],
    clearanceRequired: true,
    suggestedGoals: ["back_pain", "injury_rehab", "mobility", "posture"],
    note: "Most disc symptoms settle with graded movement. Symptoms retreating up the leg is the sign of progress.",
  },
  chronic_low_back_pain: {
    id: "chronic_low_back_pain",
    label: "Chronic low back pain",
    family: "musculoskeletal",
    avoidTags: ["loaded_spine", "spinal_flexion", "deep_twist", "high_impact", "jumping", "heavy_load"],
    cautionTags: ["sustained_forward_bend", "running_gait", "long_duration"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    preferredCategories: ["walking", "rehab", "mobility", "pilates", "swimming", "yoga", "gym_strength"],
    modifications: ["Anti-movement core work rather than crunches", "Break sitting every 30-45 minutes", "Graded exposure: increase what you avoid, slowly"],
    monitor: ["Pain score", "Sitting and standing tolerance", "Flare frequency"],
    redFlags: ["Pain below the knee with numbness", "Night pain with weight loss or fever", "Bladder or bowel changes"],
    clearanceRequired: false,
    suggestedGoals: ["back_pain", "posture", "mobility", "desk_job_reset"],
    note: "Movement, not rest, is the treatment. Fear of movement predicts poor outcomes more than imaging does.",
  },
  frozen_shoulder: {
    id: "frozen_shoulder",
    label: "Frozen shoulder / rotator cuff pain",
    family: "musculoskeletal",
    avoidTags: ["overhead_reach", "shoulder_end_range", "hanging_grip", "heavy_load", "high_impact", "explosive"],
    cautionTags: ["wrist_loading", "prone_position"],
    intensityCeiling: "light",
    maxJointLoad: "low",
    preferredCategories: ["rehab", "mobility", "walking", "cycling", "pilates"],
    modifications: [
      "Work below shoulder height until pain-free range returns",
      "Pendulum and assisted range work daily",
      "Isometric rotator cuff holds before dynamic loading",
    ],
    monitor: ["Range of motion in each direction", "Night pain"],
    redFlags: ["Sudden loss of active movement after trauma (possible tear)", "Severe unrelenting night pain"],
    clearanceRequired: false,
    suggestedGoals: ["neck_shoulder_pain", "injury_rehab", "mobility"],
    note: "Frozen shoulder passes through freezing, frozen and thawing phases; gentle daily range work shortens the course.",
  },
  plantar_fasciitis: {
    id: "plantar_fasciitis",
    label: "Plantar fasciitis / foot pain",
    family: "musculoskeletal",
    avoidTags: ["high_impact", "jumping", "running_gait", "explosive"],
    cautionTags: ["long_duration", "single_leg"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    preferredCategories: ["cycling", "swimming", "rehab", "gym_strength", "mobility"],
    modifications: ["Calf and plantar fascia loading daily", "Supportive footwear, no barefoot on hard floors", "Swap running for cycling or water work while symptomatic"],
    monitor: ["First-step-in-the-morning pain — the key marker"],
    redFlags: ["Sudden sharp pop with inability to push off (possible rupture)"],
    clearanceRequired: false,
    suggestedGoals: ["injury_rehab", "joint_pain", "weight_loss"],
    note: "Heavy slow calf raises are more effective than stretching alone.",
  },
  tendinopathy: {
    id: "tendinopathy",
    label: "Tendinopathy (Achilles / elbow / patellar)",
    family: "musculoskeletal",
    avoidTags: ["explosive", "jumping", "high_impact", "rapid_direction_change"],
    cautionTags: ["heavy_load", "hanging_grip", "single_leg", "long_duration"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    preferredCategories: ["rehab", "gym_strength", "cycling", "swimming", "mobility"],
    modifications: [
      "Isometric holds for pain relief, then heavy slow resistance",
      "Load the tendon every other day, not daily",
      "Reintroduce spring-like/explosive work last",
    ],
    monitor: ["Pain during loading and 24 hours after", "Morning stiffness"],
    redFlags: ["Sudden severe pain with a pop and loss of function"],
    clearanceRequired: false,
    suggestedGoals: ["injury_rehab", "joint_pain"],
    note: "Tendons need load to heal — complete rest weakens them. The 24-hour pain response is your dosing guide.",
  },
  joint_replacement: {
    id: "joint_replacement",
    label: "Joint replacement (hip / knee)",
    family: "musculoskeletal",
    avoidTags: ["high_impact", "jumping", "running_gait", "contact_risk", "rapid_direction_change", "deep_knee_flexion", "hip_end_range", "explosive"],
    cautionTags: ["single_leg", "balance_demand", "heavy_load"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    maxJointLoad: "moderate",
    preferredCategories: ["walking", "cycling", "swimming", "gym_strength", "rehab", "mobility"],
    modifications: [
      "Respect your surgeon's range and precaution list permanently",
      "Cycling, swimming and walking are the long-term cardio options",
      "No running or jumping — impact shortens implant life",
    ],
    monitor: ["Swelling", "Range of motion", "Gait symmetry"],
    redFlags: ["New instability or clunking", "Fever with a hot swollen joint (possible infection)", "Sudden severe pain"],
    clearanceRequired: true,
    suggestedGoals: ["injury_rehab", "post_surgery", "senior_functional", "balance_fall_prevention"],
    note: "Replaced joints do superbly with low-impact loading for decades.",
  },
  hypermobility: {
    id: "hypermobility",
    label: "Hypermobility / Ehlers-Danlos",
    family: "musculoskeletal",
    avoidTags: ["hypermobility_risk", "shoulder_end_range", "hip_end_range", "contact_risk", "high_impact", "explosive"],
    cautionTags: ["balance_demand", "heavy_load", "inversion"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    preferredCategories: ["pilates", "gym_strength", "rehab", "swimming", "walking", "mobility"],
    modifications: [
      "Strength through mid-range, never into end range",
      "Skip passive stretching — you have range already; you need control",
      "Slow controlled tempo; avoid locking out joints",
    ],
    monitor: ["Subluxation events", "Joint pain", "Fatigue"],
    redFlags: ["Frequent dislocations", "Fainting on standing (possible dysautonomia)"],
    clearanceRequired: false,
    suggestedGoals: ["mobility", "injury_rehab", "balance_fall_prevention", "energy_fatigue"],
    note: "For hypermobile bodies, stability is the goal and stretching is usually the wrong medicine.",
  },
  scoliosis: {
    id: "scoliosis",
    label: "Scoliosis",
    family: "musculoskeletal",
    avoidTags: ["loaded_spine", "high_impact", "contact_risk"],
    cautionTags: ["deep_twist", "spinal_flexion", "heavy_load"],
    intensityCeiling: "moderate",
    preferredCategories: ["swimming", "pilates", "rehab", "mobility", "gym_strength", "yoga"],
    modifications: ["Symmetrical loading with breathing into the concave side", "Core endurance work", "Avoid single-sided high-load sports"],
    monitor: ["Pain", "Breathing comfort", "Curve progression via your clinician"],
    redFlags: ["Rapid curve progression", "New breathlessness"],
    clearanceRequired: false,
    suggestedGoals: ["posture", "back_pain", "mobility", "breathing_capacity"],
    note: "Exercise cannot straighten a curve but reliably improves pain, strength and function.",
  },
  fibromyalgia: {
    id: "fibromyalgia",
    label: "Fibromyalgia / chronic widespread pain",
    family: "neurological",
    avoidTags: ["max_heart_rate", "vigorous_intensity", "long_duration", "explosive", "high_impact"],
    cautionTags: ["heavy_load", "cold_exposure"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["swimming", "walking", "yoga", "mobility", "breathwork", "recovery"],
    modifications: [
      "Start at half of what feels possible and hold it for two weeks",
      "Warm water is the best-tolerated environment",
      "Short frequent bouts; never chase intensity",
    ],
    monitor: ["Pain score", "Sleep quality", "Next-day fatigue"],
    redFlags: ["Sustained symptom worsening over weeks"],
    clearanceRequired: false,
    suggestedGoals: ["energy_fatigue", "joint_pain", "sleep_quality", "stress_calm"],
    note: "Graded, gentle, consistent activity reduces pain over time. Doing too much too soon is the classic setback.",
  },

  /* ---------------- Cardiovascular ---------------- */
  hypertension: {
    id: "hypertension",
    label: "High blood pressure",
    family: "cardiovascular",
    avoidTags: ["valsalva", "breath_retention", "inversion", "max_heart_rate"],
    cautionTags: ["heavy_load", "overhead_reach", "heat_exposure", "vigorous_intensity"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "cycling", "swimming", "breathwork", "yoga", "gym_strength"],
    modifications: [
      "Exhale on effort — never hold your breath under load",
      "Moderate loads with more reps instead of heavy straining",
      "Longer warm-up and cool-down to avoid pressure spikes and post-exercise dizziness",
      "No inversions or head-below-heart holds",
    ],
    monitor: ["Blood pressure before and after sessions initially", "Dizziness", "Headache"],
    redFlags: ["Resting BP above 180/110", "Chest pain", "Severe headache with visual change", "Breathlessness at rest"],
    clearanceRequired: false,
    suggestedGoals: ["blood_pressure", "heart_health", "weight_loss", "stress_calm"],
    note: "Aerobic exercise lowers systolic pressure by 5-8 mmHg on average — comparable to a first-line medication.",
  },
  coronary_artery_disease: {
    id: "coronary_artery_disease",
    label: "Coronary artery disease / prior heart attack",
    family: "cardiovascular",
    avoidTags: ["max_heart_rate", "valsalva", "breath_retention", "heavy_load", "explosive", "cold_exposure", "heat_exposure", "vigorous_intensity"],
    cautionTags: ["high_impact", "long_duration", "contact_risk"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["walking", "cycling", "breathwork", "gym_strength", "mobility", "swimming"],
    modifications: [
      "Stay within the heart-rate or RPE range your cardiologist or cardiac rehab set",
      "Always warm up and cool down for at least 10 minutes",
      "Carry your GTN spray if prescribed",
      "Never exercise alone until you know your response",
    ],
    monitor: ["Chest symptoms", "Breathlessness relative to effort", "Heart rate and rhythm", "Blood pressure"],
    redFlags: ["Chest pain, pressure or tightness", "Pain in jaw, neck or arm", "Unusual breathlessness", "Palpitations", "Cold sweat or nausea with effort"],
    clearanceRequired: true,
    suggestedGoals: ["heart_health", "stamina", "stress_calm", "weight_loss"],
    note: "Supervised cardiac rehabilitation reduces mortality. Get a clinician-set exercise prescription before using this plan.",
  },
  heart_failure: {
    id: "heart_failure",
    label: "Heart failure",
    family: "cardiovascular",
    avoidTags: ["max_heart_rate", "valsalva", "breath_retention", "heavy_load", "explosive", "long_duration", "heat_exposure", "cold_exposure", "vigorous_intensity", "inversion"],
    cautionTags: ["high_impact", "overhead_reach"],
    intensityCeiling: "very_light",
    maxImpact: "none",
    preferredCategories: ["walking", "breathwork", "mobility", "rehab", "recovery"],
    modifications: [
      "Very short bouts with generous rest — interval walking rather than continuous",
      "Weigh yourself daily; a 2 kg gain in 2-3 days means fluid retention, not training progress",
      "Keep sessions seated or supported when breathless",
    ],
    monitor: ["Daily weight", "Ankle swelling", "Breathlessness lying flat", "Fatigue"],
    redFlags: ["Rapid weight gain", "Breathlessness at rest or lying flat", "New or worse ankle swelling", "Fainting"],
    clearanceRequired: true,
    suggestedGoals: ["heart_health", "energy_fatigue", "breathing_capacity"],
    note: "Exercise helps heart failure, but only under a clinician-set prescription. Do not self-progress.",
  },
  arrhythmia: {
    id: "arrhythmia",
    label: "Arrhythmia / atrial fibrillation",
    family: "cardiovascular",
    avoidTags: ["max_heart_rate", "explosive", "valsalva", "breath_retention", "vigorous_intensity", "cold_exposure"],
    cautionTags: ["heavy_load", "long_duration", "high_impact"],
    intensityCeiling: "light",
    preferredCategories: ["walking", "cycling", "breathwork", "yoga", "gym_strength", "swimming"],
    modifications: [
      "Use RPE rather than heart rate — the rhythm makes HR unreliable",
      "Avoid caffeine and stimulants before sessions",
      "Stop and rest if palpitations start; do not push through",
    ],
    monitor: ["Palpitations", "Dizziness", "Exercise tolerance"],
    redFlags: ["Fainting or near-fainting", "Chest pain", "Sustained racing heart at rest"],
    clearanceRequired: true,
    suggestedGoals: ["heart_health", "stress_calm", "stamina"],
    note: "Moderate exercise is protective; extreme endurance volumes can increase atrial fibrillation risk.",
  },
  stroke_history: {
    id: "stroke_history",
    label: "Stroke / TIA history",
    family: "neurological",
    avoidTags: ["max_heart_rate", "valsalva", "breath_retention", "inversion", "fall_risk", "contact_risk", "explosive", "high_impact"],
    cautionTags: ["balance_demand", "heavy_load", "single_leg", "heat_exposure"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["walking", "rehab", "mobility", "gym_strength", "breathwork", "swimming"],
    modifications: [
      "Train balance with support always within reach",
      "Work on the affected side deliberately, in supported positions",
      "Keep blood pressure controlled; avoid straining",
    ],
    monitor: ["Blood pressure", "Balance", "Fatigue", "Any new neurological symptom"],
    redFlags: ["Face droop, arm weakness, speech difficulty — call emergency services", "Sudden severe headache", "New vision loss"],
    clearanceRequired: true,
    suggestedGoals: ["balance_fall_prevention", "injury_rehab", "heart_health", "senior_functional"],
    note: "Task-specific repetition drives neurological recovery; supervision early on is important.",
  },
  varicose_dvt: {
    id: "varicose_dvt",
    label: "Varicose veins / DVT history",
    family: "cardiovascular",
    avoidTags: ["valsalva", "heavy_load", "long_duration", "heat_exposure"],
    cautionTags: ["high_impact", "prone_position"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "swimming", "cycling", "mobility", "rehab"],
    modifications: ["Calf pump exercises and elevation after sitting", "Compression stockings if prescribed", "Avoid long static standing"],
    monitor: ["Calf pain, swelling, warmth or redness"],
    redFlags: ["Unilateral calf swelling with pain — possible DVT, seek urgent care", "Sudden breathlessness or chest pain"],
    clearanceRequired: false,
    suggestedGoals: ["heart_health", "weight_loss", "mobility"],
    note: "Walking is the single best thing for venous return. An acute DVT means no exercise until medically cleared.",
  },

  /* ---------------- Metabolic & endocrine ---------------- */
  diabetes_type2: {
    id: "diabetes_type2",
    label: "Type 2 diabetes",
    family: "metabolic_endocrine",
    avoidTags: [],
    cautionTags: ["high_impact", "max_heart_rate", "heat_exposure", "long_duration"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "gym_strength", "cycling", "swimming", "yoga"],
    modifications: [
      "Walk 10-15 minutes after each main meal — the single highest-yield habit",
      "Never let more than two days pass without exercise; insulin sensitivity fades in 48-72 hours",
      "Well-cushioned shoes and daily foot checks if you have any neuropathy",
      "Carry fast carbohydrate if you take insulin or a sulfonylurea",
    ],
    monitor: ["Blood glucose before and after sessions", "Feet for blisters or numbness", "Hydration"],
    redFlags: ["Glucose below 70 mg/dL", "Glucose above 250 mg/dL with ketones", "Foot wound or ulcer", "New vision change"],
    clearanceRequired: false,
    suggestedGoals: ["blood_sugar", "weight_loss", "heart_health", "belly_fat"],
    note: "Muscle contraction clears glucose without insulin. Combined aerobic plus resistance training beats either alone.",
  },
  diabetes_type1: {
    id: "diabetes_type1",
    label: "Type 1 diabetes",
    family: "metabolic_endocrine",
    avoidTags: [],
    cautionTags: ["max_heart_rate", "long_duration", "heat_exposure", "vigorous_intensity"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "gym_strength", "cycling", "swimming", "yoga", "sports"],
    modifications: [
      "Always carry fast-acting glucose",
      "Check glucose before, during long sessions, and after",
      "Expect delayed lows up to 12 hours after exercise, especially overnight",
      "Resistance work before cardio tends to blunt the glucose drop",
    ],
    monitor: ["Glucose before/during/after", "Ketones if glucose is high", "Overnight lows"],
    redFlags: ["Glucose below 70 mg/dL", "Glucose above 250 mg/dL with ketones — do not exercise", "Confusion or shakiness"],
    clearanceRequired: false,
    suggestedGoals: ["blood_sugar", "heart_health", "stamina", "muscle_gain"],
    note: "Exercise is entirely compatible with type 1 diabetes but needs deliberate glucose management.",
  },
  prediabetes: {
    id: "prediabetes",
    label: "Prediabetes / insulin resistance",
    family: "metabolic_endocrine",
    avoidTags: [],
    cautionTags: [],
    preferredCategories: ["walking", "gym_strength", "cycling", "hiit", "swimming"],
    modifications: ["Post-meal walks daily", "Resistance training twice weekly", "Target 5-7% body weight loss"],
    monitor: ["Fasting glucose", "Waist", "Weight"],
    redFlags: ["Excessive thirst, urination or unexplained weight loss"],
    clearanceRequired: false,
    suggestedGoals: ["blood_sugar", "weight_loss", "belly_fat", "heart_health"],
    note: "Lifestyle change cuts progression to type 2 diabetes by around 58% — more than metformin in trials.",
  },
  obesity: {
    id: "obesity",
    label: "Obesity",
    family: "metabolic_endocrine",
    avoidTags: ["high_impact", "jumping", "explosive"],
    cautionTags: ["running_gait", "heat_exposure", "long_duration", "floor_transfer", "deep_knee_flexion"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    preferredCategories: ["walking", "swimming", "cycling", "gym_strength", "functional", "mobility"],
    modifications: [
      "Start non-weight-bearing or low-impact to protect joints",
      "Chair-supported and standing options instead of floor work where getting up is hard",
      "Build duration before intensity",
      "Water-based work removes joint load entirely",
    ],
    monitor: ["Joint pain", "Breathlessness", "Skin chafing", "Blood pressure"],
    redFlags: ["Chest pain", "Severe breathlessness on mild effort", "Ankle swelling"],
    clearanceRequired: false,
    suggestedGoals: ["weight_loss", "joint_pain", "blood_sugar", "heart_health", "stamina"],
    note: "Fitness improves health outcomes even without much weight change — so activity counts from day one.",
  },
  pcos: {
    id: "pcos",
    label: "PCOS",
    family: "reproductive",
    avoidTags: [],
    cautionTags: ["max_heart_rate", "long_duration"],
    intensityCeiling: "moderate",
    preferredCategories: ["gym_strength", "walking", "yoga", "cycling", "swimming"],
    modifications: ["Resistance training 2-3 times weekly", "Moderate rather than extreme cardio volume", "Manage stress and sleep deliberately"],
    monitor: ["Cycle regularity", "Weight and waist", "Energy", "Mood"],
    redFlags: ["Cycles stopping entirely under heavy training and low intake"],
    clearanceRequired: false,
    suggestedGoals: ["pcos_hormonal", "weight_loss", "blood_sugar", "stress_calm"],
    note: "Insulin sensitivity is the lever. 5-10% weight loss often restores ovulation.",
  },
  hypothyroidism: {
    id: "hypothyroidism",
    label: "Hypothyroidism",
    family: "metabolic_endocrine",
    avoidTags: [],
    cautionTags: ["max_heart_rate", "long_duration", "cold_exposure"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "gym_strength", "yoga", "swimming", "cycling"],
    modifications: ["Start at half your expected capacity", "Longer warm-ups; recovery is slower", "Resistance work to offset metabolic slowdown"],
    monitor: ["Energy", "Weight", "Resting heart rate", "Recovery between sessions"],
    redFlags: ["Severe fatigue, swelling or very slow heart rate — review medication dose"],
    clearanceRequired: false,
    suggestedGoals: ["thyroid_support", "weight_loss", "energy_fatigue", "muscle_gain"],
    note: "Once levels are optimised on medication, normal training applies. Untreated, everything feels harder for real physiological reasons.",
  },
  hyperthyroidism: {
    id: "hyperthyroidism",
    label: "Hyperthyroidism",
    family: "metabolic_endocrine",
    avoidTags: ["max_heart_rate", "vigorous_intensity", "explosive", "heat_exposure"],
    cautionTags: ["long_duration", "heavy_load"],
    intensityCeiling: "very_light",
    preferredCategories: ["walking", "yoga", "breathwork", "mobility", "recovery"],
    modifications: ["Gentle activity only until thyroid levels are controlled", "Watch for palpitations and overheating"],
    monitor: ["Resting heart rate", "Palpitations", "Heat intolerance", "Weight"],
    redFlags: ["Racing heart at rest", "Chest pain", "Tremor with fever — possible thyroid storm, emergency"],
    clearanceRequired: true,
    suggestedGoals: ["thyroid_support", "stress_calm", "energy_fatigue"],
    note: "Vigorous exercise is deferred until the thyroid is medically controlled.",
  },

  /* ---------------- Respiratory ---------------- */
  asthma: {
    id: "asthma",
    label: "Asthma",
    family: "respiratory",
    avoidTags: ["cold_exposure", "pollen_exposure", "air_pollution_exposure", "breath_retention"],
    cautionTags: ["max_heart_rate", "vigorous_intensity", "long_duration"],
    intensityCeiling: "moderate",
    preferredCategories: ["swimming", "walking", "cycling", "yoga", "breathwork", "gym_strength"],
    modifications: [
      "Keep your reliever inhaler with you every session",
      "Use it 10-15 minutes before exercise if your doctor advised pre-treatment",
      "Extend warm-up to 15 minutes — this markedly reduces exercise-induced symptoms",
      "Train indoors on high-pollen, cold or high-pollution days; swimming's warm humid air is well tolerated",
    ],
    monitor: ["Wheeze, cough or chest tightness", "Reliever use frequency", "Peak flow if you track it"],
    redFlags: ["Reliever not working", "Difficulty speaking in full sentences", "Blue lips", "Peak flow below 50% of best"],
    clearanceRequired: false,
    suggestedGoals: ["breathing_capacity", "stamina", "heart_health", "weight_loss"],
    note: "Well-controlled asthma is not a reason to avoid exercise — fitter lungs mean fewer symptoms.",
  },
  copd: {
    id: "copd",
    label: "COPD / chronic bronchitis",
    family: "respiratory",
    avoidTags: ["breath_retention", "cold_exposure", "air_pollution_exposure", "max_heart_rate", "vigorous_intensity", "long_duration"],
    cautionTags: ["heat_exposure", "overhead_reach", "high_impact"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["walking", "breathwork", "gym_strength", "mobility", "cycling", "rehab"],
    modifications: [
      "Interval-style: 1-2 minutes of effort, then rest until breathing settles",
      "Pursed-lip breathing during exertion",
      "Sit down for upper-body work — raised arms increase breathlessness",
      "Use supplemental oxygen during exercise if prescribed",
    ],
    monitor: ["Breathlessness score", "Oxygen saturation if you have a monitor", "Sputum changes"],
    redFlags: ["Oxygen saturation below 88%", "Breathlessness at rest", "Fever with sputum change", "Confusion"],
    clearanceRequired: true,
    suggestedGoals: ["breathing_capacity", "energy_fatigue", "senior_functional"],
    note: "Pulmonary rehabilitation is one of the most effective treatments in COPD — exercise improves breathlessness even when lung function does not change.",
  },
  sleep_apnoea: {
    id: "sleep_apnoea",
    label: "Sleep apnoea",
    family: "respiratory",
    avoidTags: [],
    cautionTags: ["max_heart_rate", "long_duration"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "gym_strength", "swimming", "cycling", "breathwork"],
    modifications: ["Weight loss reduces severity substantially", "Keep using CPAP — untrained sleep debt limits everything else", "Avoid late evening intensity"],
    monitor: ["Daytime sleepiness", "Sleep hours", "Weight", "Blood pressure"],
    redFlags: ["Falling asleep while driving", "Morning headaches with chest symptoms"],
    clearanceRequired: false,
    suggestedGoals: ["weight_loss", "sleep_quality", "blood_pressure", "energy_fatigue"],
    note: "A 10% weight reduction can cut apnoea severity by around 25%.",
  },

  /* ---------------- Neurological & mental health ---------------- */
  epilepsy: {
    id: "epilepsy",
    label: "Epilepsy",
    family: "neurological",
    avoidTags: ["fall_risk", "breath_retention", "heat_exposure", "contact_risk", "hanging_grip"],
    cautionTags: ["max_heart_rate", "balance_demand"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "gym_strength", "cycling", "yoga", "mobility"],
    modifications: [
      "Never swim alone — always with a companion who knows your condition",
      "Avoid heights, climbing and solo open-water activity",
      "Stay hydrated, avoid overheating and sleep deprivation — all are seizure triggers",
    ],
    monitor: ["Seizure frequency", "Sleep", "Medication adherence"],
    redFlags: ["Increase in seizure frequency", "Seizure during activity"],
    clearanceRequired: false,
    suggestedGoals: ["heart_health", "stress_calm", "sleep_quality", "weight_loss"],
    note: "Exercise does not usually provoke seizures and often reduces frequency; the precautions are about injury if a seizure occurs.",
  },
  vertigo: {
    id: "vertigo",
    label: "Vertigo / balance disorder",
    family: "sensory",
    avoidTags: ["inversion", "fall_risk", "rapid_direction_change", "high_impact", "explosive"],
    cautionTags: ["balance_demand", "deep_twist", "single_leg", "prone_position"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["walking", "rehab", "gym_strength", "mobility", "cycling"],
    modifications: [
      "Avoid rapid head position changes and lying-to-standing transitions",
      "Train balance seated or with two hands on support",
      "Move slowly between positions",
    ],
    monitor: ["Dizziness episodes", "Nausea", "Balance confidence"],
    redFlags: ["Vertigo with new hearing loss, double vision or weakness — urgent assessment"],
    clearanceRequired: false,
    suggestedGoals: ["balance_fall_prevention", "senior_functional", "mobility"],
    note: "Vestibular rehabilitation exercises specifically retrain the balance system — worth asking your clinician about.",
  },
  depression: {
    id: "depression",
    label: "Depression",
    family: "mental_health",
    avoidTags: [],
    cautionTags: ["long_duration"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "running", "gym_strength", "yoga", "dance", "sports"],
    modifications: ["Define a 5-minute minimum version of every session", "Prefer outdoor and social formats", "Morning light exposure daily"],
    monitor: ["Mood", "Sleep", "Energy", "Adherence"],
    redFlags: ["Thoughts of self-harm — contact a professional or crisis line immediately"],
    clearanceRequired: false,
    suggestedGoals: ["mood_depression", "sleep_quality", "energy_fatigue", "stress_calm"],
    note: "Exercise has a clinically meaningful antidepressant effect and works best alongside, not instead of, treatment.",
  },
  anxiety_disorder: {
    id: "anxiety_disorder",
    label: "Anxiety disorder / panic",
    family: "mental_health",
    avoidTags: ["breath_retention", "max_heart_rate"],
    cautionTags: ["vigorous_intensity", "heat_exposure"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "breathwork", "yoga", "swimming", "meditation", "gym_strength"],
    modifications: [
      "Slow paced breathing, never fast forceful breathing drills",
      "Build intensity gradually so raised heart rate stops feeling like danger",
      "Have an exit plan for group settings — it reduces anticipatory anxiety",
    ],
    monitor: ["Anxiety level before and after", "Sleep", "Caffeine intake"],
    redFlags: ["Panic attacks increasing in frequency"],
    clearanceRequired: false,
    suggestedGoals: ["anxiety_relief", "stress_calm", "sleep_quality", "mood_depression"],
    note: "Aerobic exercise reduces anxiety sensitivity by safely exposing you to the physical sensations of arousal.",
  },
  insomnia: {
    id: "insomnia",
    label: "Insomnia",
    family: "mental_health",
    avoidTags: [],
    cautionTags: ["max_heart_rate", "vigorous_intensity"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "yoga", "breathwork", "meditation", "cycling", "recovery"],
    modifications: ["Schedule intensity before mid-afternoon", "Evening sessions limited to stretching, breathing or a gentle walk", "Fixed wake time"],
    monitor: ["Sleep hours", "Time to fall asleep", "Night wakings"],
    redFlags: ["Severe daytime sleepiness affecting driving"],
    clearanceRequired: false,
    suggestedGoals: ["sleep_quality", "stress_calm", "energy_fatigue"],
    note: "Exercise improves sleep, but timing matters: vigorous work within 3 hours of bed delays sleep onset.",
  },
  adhd: {
    id: "adhd",
    label: "ADHD",
    family: "mental_health",
    avoidTags: [],
    cautionTags: ["max_heart_rate"],
    intensityCeiling: "vigorous",
    preferredCategories: ["running", "sports", "martial_arts", "gym_strength", "dance", "hiit"],
    modifications: ["Move before demanding cognitive work", "Choose varied, engaging, skill-based activity over monotony", "Short frequent movement breaks"],
    monitor: ["Focus", "Mood", "Sleep"],
    redFlags: ["Palpitations if on stimulant medication — review with your doctor"],
    clearanceRequired: false,
    suggestedGoals: ["focus_cognition", "mood_depression", "sports_performance", "sleep_quality"],
    note: "A single bout of aerobic exercise measurably improves attention for a couple of hours afterwards.",
  },
  migraine: {
    id: "migraine",
    label: "Migraine",
    family: "neurological",
    avoidTags: ["max_heart_rate", "explosive", "inversion", "heat_exposure", "breath_retention"],
    cautionTags: ["vigorous_intensity", "neck_loading", "long_duration"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "yoga", "breathwork", "cycling", "swimming", "mobility"],
    modifications: ["Long gradual warm-ups", "Consistent daily timing", "Hydrate and eat before sessions", "Neck and shoulder mobility daily"],
    monitor: ["Migraine days per month", "Triggers", "Sleep"],
    redFlags: ["Sudden severe new headache", "Headache with weakness, speech or vision change — emergency"],
    clearanceRequired: false,
    suggestedGoals: ["migraine_relief", "stress_calm", "neck_shoulder_pain", "sleep_quality"],
    note: "Regular aerobic exercise reduces migraine frequency comparably to some preventive medications.",
  },

  /* ---------------- Digestive, renal, reproductive, immune ---------------- */
  ibs: {
    id: "ibs",
    label: "IBS",
    family: "digestive",
    avoidTags: ["intra_abdominal_pressure", "max_heart_rate"],
    cautionTags: ["long_duration", "vigorous_intensity"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "yoga", "breathwork", "cycling", "mobility"],
    modifications: ["Avoid hard sessions within 90 minutes of eating", "Diaphragmatic breathing daily", "Walk after meals"],
    monitor: ["Symptom diary", "Stress", "Sleep"],
    redFlags: ["Blood in stool", "Unexplained weight loss", "Night-time symptoms"],
    clearanceRequired: false,
    suggestedGoals: ["digestive_health", "stress_calm", "sleep_quality"],
    note: "The gut-brain axis means stress management is genuinely a digestive intervention.",
  },
  gerd: {
    id: "gerd",
    label: "Acid reflux / GERD",
    family: "digestive",
    avoidTags: ["inversion", "intra_abdominal_pressure", "sustained_forward_bend"],
    cautionTags: ["spinal_flexion", "prone_position", "max_heart_rate"],
    intensityCeiling: "moderate",
    preferredCategories: ["walking", "cycling", "gym_strength", "breathwork", "swimming"],
    modifications: ["Do not exercise within 2 hours of a large meal", "Avoid inversions and deep forward folds", "Upright cardio suits best"],
    monitor: ["Reflux episodes around sessions"],
    redFlags: ["Difficulty swallowing", "Vomiting blood", "Chest pain that could be cardiac"],
    clearanceRequired: false,
    suggestedGoals: ["weight_loss", "digestive_health", "belly_fat"],
    note: "Weight loss and upright activity both reduce reflux; abdominal compression makes it worse.",
  },
  ckd: {
    id: "ckd",
    label: "Chronic kidney disease",
    family: "renal_hepatic",
    avoidTags: ["max_heart_rate", "heat_exposure", "valsalva", "heavy_load", "vigorous_intensity"],
    cautionTags: ["long_duration", "high_impact"],
    intensityCeiling: "light",
    preferredCategories: ["walking", "cycling", "gym_strength", "mobility", "yoga"],
    modifications: ["Moderate protein per your nephrologist's advice", "Careful hydration — both too little and too much matter", "Avoid exercising on dialysis days if advised"],
    monitor: ["Blood pressure", "Fatigue", "Swelling", "Weight"],
    redFlags: ["Severe swelling", "Breathlessness", "Very low urine output"],
    clearanceRequired: true,
    suggestedGoals: ["heart_health", "energy_fatigue", "senior_functional"],
    note: "Exercise improves function and quality of life in CKD; hydration and protein need clinician input.",
  },
  hernia: {
    id: "hernia",
    label: "Hernia (inguinal / abdominal)",
    family: "digestive",
    avoidTags: ["intra_abdominal_pressure", "valsalva", "heavy_load", "high_impact", "jumping", "spinal_flexion"],
    cautionTags: ["explosive", "hanging_grip"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["walking", "swimming", "mobility", "rehab", "breathwork"],
    modifications: ["Exhale on every effort, never brace against a closed throat", "No heavy lifting or crunching", "Support the area if advised"],
    monitor: ["Bulge size", "Discomfort with activity"],
    redFlags: ["Hernia becoming hard, painful or irreducible with vomiting — emergency, possible strangulation"],
    clearanceRequired: true,
    suggestedGoals: ["injury_rehab", "weight_loss", "mobility"],
    note: "Intra-abdominal pressure is the mechanism of worsening, so breathing technique is the main safeguard.",
  },
  pelvic_organ_prolapse: {
    id: "pelvic_organ_prolapse",
    label: "Pelvic organ prolapse / incontinence",
    family: "reproductive",
    avoidTags: ["high_impact", "jumping", "intra_abdominal_pressure", "valsalva", "heavy_load", "pelvic_floor_load", "running_gait"],
    cautionTags: ["spinal_flexion", "explosive", "long_duration"],
    intensityCeiling: "light",
    maxImpact: "none",
    preferredCategories: ["rehab", "pilates", "swimming", "walking", "breathwork", "yoga"],
    modifications: [
      "Exhale on effort, every time",
      "Progress from lying to sitting to standing loading",
      "Swap running and jumping for swimming, cycling or brisk walking",
    ],
    monitor: ["Heaviness or bulging sensation", "Leaking", "Symptoms worse late in the day"],
    redFlags: ["Visible bulge", "New or worsening leaking with activity"],
    clearanceRequired: false,
    suggestedGoals: ["pelvic_floor", "postpartum", "weight_loss"],
    note: "A pelvic health physiotherapist can transform outcomes here — worth prioritising over any generic plan.",
  },
  pregnancy: {
    id: "pregnancy",
    label: "Pregnancy",
    family: "reproductive",
    avoidTags: [
      "high_impact", "jumping", "contact_risk", "fall_risk", "supine_position", "prone_position", "inversion",
      "deep_twist", "breath_retention", "valsalva", "heat_exposure", "intra_abdominal_pressure", "max_heart_rate",
      "spinal_flexion", "rapid_direction_change", "explosive", "hanging_grip",
    ],
    cautionTags: ["balance_demand", "single_leg", "heavy_load", "long_duration"],
    intensityCeiling: "moderate",
    maxImpact: "low",
    preferredCategories: ["walking", "swimming", "yoga", "pilates", "rehab", "breathwork"],
    modifications: [
      "No exercise lying flat on your back after about week 16",
      "Talk test throughout — you should be able to hold a conversation",
      "Avoid overheating; stay well hydrated and out of hot rooms",
      "No contact sport, no activity with fall risk, no scuba diving or altitude",
      "Pelvic floor and breathing work daily",
    ],
    monitor: ["Fetal movement", "Breathlessness relative to effort", "Pelvic pain", "Any bleeding"],
    redFlags: [
      "Vaginal bleeding or fluid leakage",
      "Regular painful contractions",
      "Dizziness, chest pain or headache",
      "Calf pain or swelling",
      "Reduced fetal movement",
    ],
    clearanceRequired: true,
    suggestedGoals: ["prenatal", "pelvic_floor", "back_pain", "stress_calm"],
    note: "150 minutes of moderate activity weekly is recommended in uncomplicated pregnancy, and lowers gestational diabetes and pre-eclampsia risk.",
  },
  postpartum: {
    id: "postpartum",
    label: "Postpartum (0-12 months)",
    family: "reproductive",
    avoidTags: ["high_impact", "jumping", "intra_abdominal_pressure", "valsalva", "spinal_flexion", "heavy_load", "pelvic_floor_load", "running_gait"],
    cautionTags: ["deep_twist", "explosive", "single_leg", "long_duration"],
    intensityCeiling: "light",
    maxImpact: "none",
    preferredCategories: ["rehab", "walking", "pilates", "breathwork", "yoga", "swimming"],
    modifications: [
      "Breath and pelvic floor first; core loading second; impact last",
      "No running or jumping before 12 weeks and only once leak-free and pain-free",
      "Check for doming along the midline during core work — if it doms, regress",
      "Caesarean recovery needs longer before any core loading",
    ],
    monitor: ["Bleeding", "Leaking", "Heaviness", "Abdominal doming", "Fatigue"],
    redFlags: ["Heavy bleeding returning", "Fever", "Severe pain", "Wound issues"],
    clearanceRequired: false,
    suggestedGoals: ["postpartum", "pelvic_floor", "back_pain", "energy_fatigue"],
    note: "A staged 12-24 week return is normal and protective. Rushing impact is the main cause of long-term pelvic floor problems.",
  },
  menopause: {
    id: "menopause",
    label: "Peri/post-menopause",
    family: "reproductive",
    avoidTags: ["heat_exposure"],
    cautionTags: ["high_impact", "max_heart_rate"],
    intensityCeiling: "vigorous",
    preferredCategories: ["gym_strength", "walking", "yoga", "functional", "swimming", "dance"],
    modifications: ["Resistance training is the priority for bone and muscle", "Cool environments for evening sessions", "Protein 1.6-2.0 g/kg"],
    monitor: ["Sleep", "Hot flush frequency", "Strength", "Weight and waist"],
    redFlags: ["Any post-menopausal bleeding needs medical assessment"],
    clearanceRequired: false,
    suggestedGoals: ["menopause_support", "bone_density", "muscle_gain", "sleep_quality"],
    note: "Muscle and bone loss accelerate here; resistance training is the countermeasure with the best evidence.",
  },
  anaemia: {
    id: "anaemia",
    label: "Anaemia / low iron",
    family: "other",
    avoidTags: ["max_heart_rate", "vigorous_intensity", "long_duration"],
    cautionTags: ["heat_exposure", "high_impact"],
    intensityCeiling: "light",
    preferredCategories: ["walking", "yoga", "mobility", "gym_strength", "breathwork"],
    modifications: ["Reduce volume until iron is corrected", "Expect a higher heart rate at the same effort", "Rise slowly from the floor"],
    monitor: ["Breathlessness", "Dizziness", "Energy", "Heart rate at rest"],
    redFlags: ["Fainting", "Chest pain", "Severe breathlessness"],
    clearanceRequired: false,
    suggestedGoals: ["energy_fatigue", "stamina"],
    note: "Treat the anaemia first — training on low haemoglobin feels disproportionately hard for a real reason.",
  },
  cancer_treatment: {
    id: "cancer_treatment",
    label: "Cancer — in treatment or recent",
    family: "immune_oncology",
    avoidTags: ["contact_risk", "max_heart_rate", "heat_exposure", "high_impact", "vigorous_intensity"],
    cautionTags: ["heavy_load", "long_duration", "chlorine_exposure", "explosive"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["walking", "gym_strength", "yoga", "mobility", "breathwork", "rehab"],
    modifications: [
      "Flex volume with treatment cycles — lighter on and after treatment days",
      "Avoid pools and crowded gyms when immune counts are low or with a central line",
      "Progress upper-body load slowly if you are at lymphoedema risk",
      "Resistance work protects muscle through treatment",
    ],
    monitor: ["Fatigue", "Blood counts (via your team)", "Weight", "Neuropathy and balance"],
    redFlags: ["Fever", "New bone pain", "Uncontrolled nausea or vomiting", "Severe breathlessness", "Unusual bruising or bleeding"],
    clearanceRequired: true,
    suggestedGoals: ["cancer_recovery", "energy_fatigue", "muscle_gain", "stress_calm"],
    note: "Exercise during treatment reduces fatigue and preserves function. Coordinate with your oncology team.",
  },
  immunocompromised: {
    id: "immunocompromised",
    label: "Immunocompromised",
    family: "immune_oncology",
    avoidTags: ["contact_risk", "max_heart_rate", "chlorine_exposure", "vigorous_intensity"],
    cautionTags: ["long_duration", "air_pollution_exposure"],
    intensityCeiling: "light",
    preferredCategories: ["walking", "gym_strength", "yoga", "mobility", "breathwork"],
    modifications: ["Prefer home or outdoor uncrowded settings", "Avoid shared equipment without wiping down", "Do not train when unwell at all"],
    monitor: ["Infection signs", "Fatigue", "Recovery time"],
    redFlags: ["Fever", "New cough or breathlessness"],
    clearanceRequired: false,
    suggestedGoals: ["immunity", "energy_fatigue", "maintain_weight"],
    note: "Moderate exercise supports immune function; heavy training loads suppress it.",
  },
  long_covid: {
    id: "long_covid",
    label: "Long COVID / post-viral syndrome",
    family: "other",
    avoidTags: ["max_heart_rate", "vigorous_intensity", "long_duration", "heat_exposure", "explosive", "high_impact"],
    cautionTags: ["balance_demand", "heavy_load"],
    intensityCeiling: "very_light",
    maxImpact: "low",
    preferredCategories: ["breathwork", "walking", "mobility", "yoga", "recovery", "rehab"],
    modifications: [
      "Stay below the effort that causes next-day symptoms — pacing, not progression",
      "Very short bouts with full rest",
      "Hold each level for a full week before adding anything",
      "Position changes slowly if you get dizzy standing",
    ],
    monitor: ["Next-day symptoms", "Resting heart rate", "Heart rate on standing", "Energy"],
    redFlags: ["Chest pain", "Palpitations", "Fainting on exertion", "Worsening over weeks"],
    clearanceRequired: true,
    suggestedGoals: ["long_covid", "energy_fatigue", "breathing_capacity", "stress_calm"],
    note: "Where post-exertional malaise is present, standard progressive exercise makes people worse. Pacing is the treatment.",
  },
  recent_surgery: {
    id: "recent_surgery",
    label: "Surgery in the last 3 months",
    family: "other",
    avoidTags: ["heavy_load", "high_impact", "jumping", "intra_abdominal_pressure", "valsalva", "explosive", "contact_risk", "hanging_grip", "max_heart_rate"],
    cautionTags: ["spinal_flexion", "overhead_reach", "long_duration", "balance_demand"],
    intensityCeiling: "very_light",
    maxImpact: "none",
    preferredCategories: ["walking", "rehab", "breathwork", "mobility"],
    modifications: [
      "Your surgeon's restrictions override everything in this plan",
      "Short frequent walks to reduce clot risk",
      "Breathing exercises after chest or abdominal surgery",
      "No lifting beyond your prescribed limit",
    ],
    monitor: ["Wound", "Pain", "Swelling", "Temperature"],
    redFlags: ["Wound redness, discharge or opening", "Fever", "Calf pain or swelling", "Sudden breathlessness or chest pain"],
    clearanceRequired: true,
    suggestedGoals: ["post_surgery", "injury_rehab", "energy_fatigue"],
    note: "Early gentle movement speeds recovery; loading too early costs weeks.",
  },
  glaucoma_retinopathy: {
    id: "glaucoma_retinopathy",
    label: "Glaucoma / diabetic retinopathy",
    family: "sensory",
    avoidTags: ["inversion", "valsalva", "breath_retention", "heavy_load", "high_impact", "jumping", "contact_risk"],
    cautionTags: ["sustained_forward_bend", "max_heart_rate"],
    intensityCeiling: "light",
    maxImpact: "low",
    preferredCategories: ["walking", "cycling", "swimming", "gym_strength", "mobility"],
    modifications: ["No head-down positions or inversions — they raise eye pressure", "Never strain or hold your breath under load", "Moderate loads with controlled breathing"],
    monitor: ["Vision changes", "Eye pain"],
    redFlags: ["Sudden vision loss, floaters or flashes — urgent ophthalmology review"],
    clearanceRequired: true,
    suggestedGoals: ["blood_sugar", "heart_health", "weight_loss"],
    note: "With proliferative retinopathy, avoid straining and jarring activity to reduce haemorrhage risk.",
  },
};

export const CONDITION_LIST: ConditionDefinition[] = Object.values(CONDITIONS);

export const CONDITION_FAMILY_LABELS: Record<string, string> = {
  musculoskeletal: "Bones, joints & muscles",
  cardiovascular: "Heart & circulation",
  metabolic_endocrine: "Metabolic & hormonal",
  respiratory: "Lungs & breathing",
  neurological: "Brain & nerves",
  mental_health: "Mental health",
  digestive: "Digestive",
  reproductive: "Reproductive & pelvic health",
  immune_oncology: "Immune & cancer",
  renal_hepatic: "Kidney & liver",
  sensory: "Eyes & balance",
  other: "Other",
};

/* ------------------------------------------------------------------ *
 * Medications
 * ------------------------------------------------------------------ */

export const MEDICATIONS: Record<string, MedicationDefinition> = {
  beta_blocker: {
    id: "beta_blocker",
    label: "Beta blocker",
    examples: ["metoprolol", "atenolol", "bisoprolol", "propranolol"],
    exerciseImplications: [
      "Blunts heart rate, so heart-rate targets and zone training are meaningless — use RPE instead",
      "Reduces maximum exercise capacity; expect to feel effort at lower heart rates",
      "Can cause cold hands and feet; warm up longer",
    ],
    avoidTags: ["max_heart_rate"],
    intensityCeiling: "moderate",
    invalidatesHeartRateZones: true,
    monitor: ["RPE", "Dizziness on standing", "Fatigue"],
  },
  insulin: {
    id: "insulin",
    label: "Insulin",
    examples: ["basal insulin", "rapid-acting insulin"],
    exerciseImplications: [
      "Real hypoglycaemia risk during and up to 12 hours after exercise, especially overnight",
      "Always carry fast-acting carbohydrate",
      "Avoid injecting into a limb you are about to work hard",
      "Resistance work before cardio reduces the glucose drop",
    ],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["Glucose before, during long sessions, and after", "Overnight lows"],
  },
  sulfonylurea: {
    id: "sulfonylurea",
    label: "Sulfonylurea",
    examples: ["glimepiride", "gliclazide", "glipizide"],
    exerciseImplications: ["Causes hypoglycaemia with exercise", "Carry fast carbohydrate", "Check glucose around sessions"],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["Glucose before and after", "Shakiness or confusion"],
  },
  metformin: {
    id: "metformin",
    label: "Metformin",
    examples: ["metformin"],
    exerciseImplications: ["Low hypoglycaemia risk on its own", "Can cause GI upset — avoid hard sessions right after a dose"],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["GI symptoms", "Hydration"],
  },
  anticoagulant: {
    id: "anticoagulant",
    label: "Blood thinner / anticoagulant",
    examples: ["warfarin", "apixaban", "rivaroxaban", "clopidogrel"],
    exerciseImplications: [
      "Avoid contact and collision sports and anything with a real fall risk — bleeding risk",
      "Bruising more easily is expected",
      "Head impact of any kind needs medical review",
    ],
    avoidTags: ["contact_risk", "fall_risk", "high_impact"],
    invalidatesHeartRateZones: false,
    monitor: ["Unusual bruising or bleeding", "Any head knock"],
  },
  diuretic: {
    id: "diuretic",
    label: "Diuretic",
    examples: ["furosemide", "hydrochlorothiazide", "indapamide"],
    exerciseImplications: [
      "Increases dehydration and electrolyte-loss risk, especially in heat",
      "Can cause dizziness on standing — cool down gradually",
    ],
    avoidTags: ["heat_exposure"],
    invalidatesHeartRateZones: false,
    monitor: ["Hydration", "Dizziness", "Cramping", "Weight"],
  },
  ace_inhibitor: {
    id: "ace_inhibitor",
    label: "ACE inhibitor / ARB",
    examples: ["ramipril", "lisinopril", "losartan", "telmisartan"],
    exerciseImplications: ["Post-exercise blood pressure can drop — extend your cool-down", "Dry cough may affect breathing comfort"],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["Dizziness after sessions", "Blood pressure"],
  },
  statin: {
    id: "statin",
    label: "Statin",
    examples: ["atorvastatin", "rosuvastatin", "simvastatin"],
    exerciseImplications: ["Muscle aches are possible, particularly when adding new load", "Progress load gradually and report persistent muscle pain"],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["Muscle pain or weakness", "Dark urine (rare but urgent)"],
  },
  corticosteroid: {
    id: "corticosteroid",
    label: "Corticosteroid",
    examples: ["prednisolone", "dexamethasone"],
    exerciseImplications: [
      "Long-term use weakens tendon and bone — progress load slowly and avoid impact spikes",
      "Raises blood glucose and can cause muscle wasting; resistance training helps counter it",
    ],
    avoidTags: ["high_impact", "explosive"],
    intensityCeiling: "moderate",
    invalidatesHeartRateZones: false,
    monitor: ["Glucose", "Tendon pain", "Blood pressure", "Weight"],
  },
  thyroid_replacement: {
    id: "thyroid_replacement",
    label: "Thyroid hormone replacement",
    examples: ["levothyroxine"],
    exerciseImplications: ["Once dose is stable, normal training applies", "Palpitations may mean the dose is too high — review it"],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["Resting heart rate", "Energy", "Palpitations"],
  },
  ssri: {
    id: "ssri",
    label: "Antidepressant (SSRI/SNRI)",
    examples: ["sertraline", "fluoxetine", "escitalopram", "venlafaxine"],
    exerciseImplications: ["May cause dizziness or sweating early on", "Exercise adds to the treatment effect — keep both"],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["Dizziness", "Hydration", "Mood"],
  },
  stimulant_adhd: {
    id: "stimulant_adhd",
    label: "ADHD stimulant",
    examples: ["methylphenidate", "amphetamine salts"],
    exerciseImplications: ["Raises resting heart rate and blood pressure — heart-rate targets read high", "Avoid stacking maximal intensity on peak dose"],
    avoidTags: ["max_heart_rate"],
    invalidatesHeartRateZones: true,
    monitor: ["Heart rate", "Blood pressure", "Palpitations", "Appetite"],
  },
  bronchodilator: {
    id: "bronchodilator",
    label: "Inhaler / bronchodilator",
    examples: ["salbutamol", "formoterol", "budesonide"],
    exerciseImplications: ["Keep the reliever with you at every session", "Pre-exercise use 10-15 minutes before, if prescribed", "Can cause tremor and raised heart rate"],
    avoidTags: ["cold_exposure", "pollen_exposure", "air_pollution_exposure"],
    invalidatesHeartRateZones: false,
    monitor: ["Reliever use frequency", "Wheeze", "Heart rate"],
  },
  opioid_analgesic: {
    id: "opioid_analgesic",
    label: "Opioid painkiller",
    examples: ["tramadol", "codeine", "morphine"],
    exerciseImplications: [
      "Masks pain, so you can overload tissue without feeling it — keep load conservative",
      "Causes drowsiness and impairs balance and coordination",
    ],
    avoidTags: ["balance_demand", "fall_risk", "heavy_load", "high_impact"],
    intensityCeiling: "light",
    invalidatesHeartRateZones: false,
    monitor: ["Drowsiness", "Balance", "Pain after sessions"],
  },
  nsaid: {
    id: "nsaid",
    label: "NSAID / anti-inflammatory",
    examples: ["ibuprofen", "naproxen", "diclofenac"],
    exerciseImplications: ["Masks pain — do not use it to push through a session", "May blunt training adaptation and irritate the stomach; avoid on an empty stomach before long sessions"],
    avoidTags: [],
    invalidatesHeartRateZones: false,
    monitor: ["Stomach symptoms", "Actual pain level without medication"],
  },
  immunosuppressant: {
    id: "immunosuppressant",
    label: "Immunosuppressant / biologic",
    examples: ["methotrexate", "adalimumab", "tacrolimus"],
    exerciseImplications: ["Higher infection risk — prefer home or uncrowded settings", "Fatigue after dosing days is common; schedule lighter sessions then"],
    avoidTags: ["contact_risk", "chlorine_exposure"],
    intensityCeiling: "moderate",
    invalidatesHeartRateZones: false,
    monitor: ["Infection signs", "Fatigue pattern around doses"],
  },
  chemotherapy: {
    id: "chemotherapy",
    label: "Chemotherapy / active cancer treatment",
    examples: ["various cytotoxic agents"],
    exerciseImplications: [
      "Capacity swings with the treatment cycle — plan lighter days around infusions",
      "Neuropathy affects balance; train balance with support",
      "Avoid pools and crowds when counts are low",
    ],
    avoidTags: ["contact_risk", "max_heart_rate", "chlorine_exposure", "vigorous_intensity"],
    intensityCeiling: "light",
    invalidatesHeartRateZones: false,
    monitor: ["Fatigue", "Blood counts via your team", "Balance", "Fever"],
  },
};

export const MEDICATION_LIST: MedicationDefinition[] = Object.values(MEDICATIONS);

export function getCondition(id: string): ConditionDefinition | undefined {
  return CONDITIONS[id];
}

export function getMedication(id: string): MedicationDefinition | undefined {
  return MEDICATIONS[id];
}

export function conditionsByFamily(): { family: string; label: string; conditions: ConditionDefinition[] }[] {
  const map = new Map<string, ConditionDefinition[]>();
  for (const condition of CONDITION_LIST) {
    const list = map.get(condition.family) ?? [];
    list.push(condition);
    map.set(condition.family, list);
  }
  return [...map.entries()].map(([family, conditions]) => ({
    family,
    label: CONDITION_FAMILY_LABELS[family] ?? family,
    conditions,
  }));
}
