/**
 * Goal catalog — the "purpose" layer of the planner.
 *
 * Every goal declares how the week should be weighted across training
 * stimuli, what to keep out, how hard to push, what to measure and what
 * progress should look like. The engine merges the user's selected goals
 * (primary goal weighted double) into one prescription.
 */

import type { GoalDefinition, GoalId } from "./types";

export const GOALS: Record<GoalId, GoalDefinition> = {
  /* ------------------------------------------------------------------ *
   * Body composition
   * ------------------------------------------------------------------ */
  weight_loss: {
    id: "weight_loss",
    label: "Lose weight",
    purpose: "Reduce body fat at a sustainable rate without losing muscle or energy.",
    family: "body_composition",
    mechanism:
      "Fat loss is driven by a modest, consistent energy deficit. Strength work protects the muscle that keeps your metabolic rate high, steady cardio adds burn you can recover from, and a high daily step count quietly does more work than any single session.",
    bucketWeights: { cardio_steady: 8, strength: 7, cardio_interval: 4, mobility_flexibility: 3, active_recovery: 2 },
    primaryCategories: ["walking", "gym_strength", "cycling", "running", "hiit", "swimming"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 25, target: 45, max: 75 },
    weeklyMinutesTarget: 250,
    progressionRate: 0.1,
    energyBalance: "deficit",
    proteinGPerKg: 1.6,
    keyMetrics: ["weight", "waist", "steps", "active_minutes", "calories_burned", "adherence"],
    nonNegotiables: [
      "Hit your daily step target — it outweighs any single workout",
      "Two full-body strength sessions a week to protect muscle",
      "Protein at every main meal",
      "Sleep 7+ hours; short sleep raises hunger hormones",
    ],
    cautions: [
      "Do not exceed a 500-750 kcal daily deficit — faster loss costs muscle",
      "Plateaus at 6-10 weeks are normal; hold the habit, adjust intake slightly",
    ],
    successSignals: ["0.4-0.8 kg per week", "Waist shrinking even when weight stalls", "Clothes fitting differently"],
    expectedTimeline: "Visible change in 4-6 weeks; meaningful change in 12 weeks",
  },
  belly_fat: {
    id: "belly_fat",
    label: "Reduce belly fat",
    purpose: "Shrink waist circumference and visceral fat, the fat that drives metabolic risk.",
    family: "body_composition",
    mechanism:
      "Visceral fat responds strongly to overall energy deficit plus vigorous cardio, and to lower cortisol. Spot exercises do not burn belly fat, but core work improves posture so the waist looks and functions better.",
    bucketWeights: { cardio_steady: 7, cardio_interval: 6, strength: 6, mindbody_calm: 4, mobility_flexibility: 2 },
    primaryCategories: ["walking", "running", "hiit", "gym_strength", "cycling"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 25, target: 45, max: 70 },
    weeklyMinutesTarget: 250,
    progressionRate: 0.1,
    energyBalance: "deficit",
    proteinGPerKg: 1.6,
    keyMetrics: ["waist", "weight", "steps", "active_minutes", "stress", "sleep_hours"],
    nonNegotiables: ["Measure waist weekly, same time of day", "Walk 10-15 min after your largest meal", "Protect sleep and manage stress — cortisol parks fat centrally"],
    cautions: ["Crunches alone will not reduce waist size", "Alcohol is the single biggest lever for many people"],
    successSignals: ["Waist down 2-4 cm in 8 weeks", "Waist-to-height ratio moving below 0.5"],
    expectedTimeline: "8-12 weeks for a clear waist change",
  },
  weight_gain: {
    id: "weight_gain",
    label: "Gain healthy weight",
    purpose: "Add body weight as muscle and strength rather than fat.",
    family: "body_composition",
    mechanism:
      "A small calorie surplus plus progressive resistance training pushes tissue growth. Cardio is kept short so it does not eat into the surplus, but never removed — heart health still matters.",
    bucketWeights: { strength: 9, mobility_flexibility: 3, cardio_steady: 2, active_recovery: 2 },
    primaryCategories: ["gym_strength", "functional", "mobility"],
    avoidTags: ["long_duration"],
    intensityCap: "vigorous",
    sessionMinutes: { min: 30, target: 50, max: 75 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.08,
    energyBalance: "surplus",
    proteinGPerKg: 1.8,
    keyMetrics: ["weight", "strength_load", "body_fat", "adherence"],
    nonNegotiables: ["Eat in a 300-500 kcal surplus", "Add load or reps every week", "Do not skip meals on rest days"],
    cautions: ["Gaining faster than 0.5 kg/week is mostly fat", "Unexplained weight loss needs medical review, not a gym plan"],
    successSignals: ["0.25-0.5 kg per week", "Lifts climbing steadily"],
    expectedTimeline: "Strength gains in 3-4 weeks; visible size in 10-12 weeks",
  },
  muscle_gain: {
    id: "muscle_gain",
    label: "Build muscle",
    purpose: "Increase muscle size and strength across the whole body.",
    family: "body_composition",
    mechanism:
      "Muscle grows from progressive mechanical tension and enough protein and recovery. Each muscle group is trained about twice a week, close enough to failure to matter, with 48 hours between sessions for the same group.",
    bucketWeights: { strength: 10, mobility_flexibility: 3, cardio_steady: 2, active_recovery: 2 },
    primaryCategories: ["gym_strength", "functional"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 35, target: 55, max: 80 },
    weeklyMinutesTarget: 200,
    progressionRate: 0.08,
    energyBalance: "mild_surplus",
    proteinGPerKg: 1.8,
    keyMetrics: ["strength_load", "weight", "body_fat", "adherence", "rpe"],
    nonNegotiables: ["Train each muscle group twice weekly", "Last 2-3 reps of a set should be genuinely hard", "1.6-2.0 g protein per kg body weight"],
    cautions: ["Soreness is not a measure of progress", "Sleep debt blunts muscle growth more than a missed set"],
    successSignals: ["Adding reps or load every 1-2 weeks", "Circumference gains at arms/legs/chest"],
    expectedTimeline: "Neural strength in 2-4 weeks; visible hypertrophy in 8-12 weeks",
  },
  body_recomposition: {
    id: "body_recomposition",
    label: "Get leaner and stronger",
    purpose: "Lose fat and gain muscle at the same time.",
    family: "body_composition",
    mechanism:
      "Recomposition works at maintenance or a very small deficit with high protein and hard resistance training. Progress shows in the mirror and the tape rather than on the scale.",
    bucketWeights: { strength: 9, cardio_steady: 5, cardio_interval: 3, mobility_flexibility: 3 },
    primaryCategories: ["gym_strength", "walking", "hiit", "functional"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 30, target: 50, max: 75 },
    weeklyMinutesTarget: 240,
    progressionRate: 0.09,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.8,
    keyMetrics: ["waist", "weight", "strength_load", "body_fat", "adherence"],
    nonNegotiables: ["Judge progress by tape and lifts, not the scale", "Protein at 1.8 g/kg", "Never sacrifice strength sessions for cardio"],
    cautions: ["Slower than pure fat loss or pure gain — patience is the requirement"],
    successSignals: ["Weight flat while waist drops and lifts rise"],
    expectedTimeline: "12-16 weeks for a clear recomposition",
  },
  maintain_weight: {
    id: "maintain_weight",
    label: "Stay fit and maintain",
    purpose: "Hold your current shape and health with a sustainable routine.",
    family: "body_composition",
    mechanism:
      "Maintenance is about consistency across all the qualities: cardio for the heart, strength for muscle and bone, mobility for joints, and calm for the nervous system.",
    bucketWeights: { cardio_steady: 6, strength: 6, mobility_flexibility: 4, mindbody_calm: 3, sport_play: 3 },
    primaryCategories: ["walking", "gym_strength", "yoga", "sports", "cycling"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 25, target: 40, max: 60 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["weight", "active_minutes", "steps", "adherence", "energy"],
    nonNegotiables: ["Move every day, even if only a walk", "Two strength sessions a week"],
    cautions: ["Long unplanned breaks are the main risk — plan a minimum version of each session"],
    successSignals: ["Weight stable within 2 kg", "Energy steady through the week"],
    expectedTimeline: "Ongoing",
  },

  /* ------------------------------------------------------------------ *
   * Musculoskeletal
   * ------------------------------------------------------------------ */
  joint_pain: {
    id: "joint_pain",
    label: "Reduce joint pain",
    purpose: "Move with less pain and stiffness in the joints you feel it most.",
    family: "musculoskeletal",
    mechanism:
      "Joints are nourished by movement — cartilage has no blood supply and depends on load cycles for fluid exchange. The plan builds the muscle that offloads the joint, keeps sessions low-impact, and uses frequent short bouts instead of long punishing ones. Pain typically drops as strength around the joint rises.",
    bucketWeights: { rehab_corrective: 8, strength: 6, mobility_flexibility: 7, cardio_steady: 5, mindbody_calm: 3, active_recovery: 3 },
    primaryCategories: ["rehab", "mobility", "swimming", "walking", "yoga", "gym_strength", "pilates"],
    avoidTags: ["high_impact", "jumping", "running_gait", "explosive", "rapid_direction_change", "deep_knee_flexion"],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 30, max: 45 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.05,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.4,
    keyMetrics: ["pain_score", "stiffness_minutes", "range_of_motion", "active_minutes", "weight", "adherence"],
    nonNegotiables: [
      "Warm up the joint for 5-10 minutes before loading it",
      "Use the 24-hour rule: pain worse the next day means the dose was too high",
      "Strengthen the muscles above and below the painful joint",
      "Every kilo of body weight is 3-4 kg of force through the knee — weight matters",
    ],
    cautions: [
      "Never push through sharp, catching or radiating pain",
      "A pain score of 4/10 during movement is an acceptable working ceiling; higher means back off",
      "Sudden joint swelling, locking or giving way needs clinical review",
    ],
    successSignals: ["Morning stiffness shorter", "Stairs and getting up from a chair easier", "Pain score down 1-2 points"],
    expectedTimeline: "Stiffness eases in 2-3 weeks; strength-driven pain relief at 6-12 weeks",
  },
  arthritis: {
    id: "arthritis",
    label: "Manage arthritis",
    purpose: "Keep arthritic joints mobile and strong, and reduce flare frequency.",
    family: "musculoskeletal",
    mechanism:
      "In both osteoarthritis and inflammatory arthritis, exercise is a first-line treatment, not a risk. Range-of-motion work fights stiffness, low-load strength work stabilises the joint, and warm-water or non-weight-bearing cardio keeps the heart trained without grinding the joint. Volume is adjusted down during flares rather than stopped entirely.",
    bucketWeights: { mobility_flexibility: 8, rehab_corrective: 8, strength: 5, cardio_steady: 5, mindbody_calm: 4, active_recovery: 4 },
    primaryCategories: ["mobility", "rehab", "swimming", "yoga", "walking", "pilates", "breathwork"],
    avoidTags: ["high_impact", "jumping", "running_gait", "explosive", "heavy_load", "rapid_direction_change", "contact_risk", "deep_knee_flexion", "hanging_grip"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 25, max: 40 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.04,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.4,
    keyMetrics: ["pain_score", "stiffness_minutes", "range_of_motion", "adherence", "mood", "sleep_quality"],
    nonNegotiables: [
      "Daily gentle range-of-motion work, even on flare days — reduce range, not frequency",
      "Warm the joint first: warm shower, warm water pool, or 10 minutes of easy movement",
      "Split movement into 2-3 short bouts a day rather than one long session",
      "Prefer water-based and seated options when weight-bearing hurts",
    ],
    cautions: [
      "During an active inflammatory flare, drop to gentle range-of-motion and isometrics only",
      "Rheumatoid arthritis with systemic flare (fever, multiple hot swollen joints) means rest and a call to your rheumatologist",
      "Avoid gripping heavy weights if hands are affected — use straps, machines or bands",
    ],
    successSignals: ["Morning stiffness under 30 minutes", "Fewer flare days per month", "More range at the affected joint"],
    expectedTimeline: "Stiffness improves in 2-4 weeks; function and pain at 8-12 weeks",
  },
  knee_pain: {
    id: "knee_pain",
    label: "Fix knee pain",
    purpose: "Build knees that handle stairs, squats and walking without pain.",
    family: "musculoskeletal",
    mechanism:
      "Most non-traumatic knee pain improves when the quadriceps, glutes and calves get stronger and the load is progressed gradually. Isometric holds reduce pain quickly; closed-chain strength restores capacity. Impact is reintroduced only once pain-free walking is comfortable.",
    bucketWeights: { rehab_corrective: 9, strength: 7, mobility_flexibility: 5, cardio_steady: 4, balance_coordination: 3 },
    primaryCategories: ["rehab", "gym_strength", "cycling", "swimming", "mobility", "walking"],
    avoidTags: ["high_impact", "jumping", "running_gait", "deep_knee_flexion", "rapid_direction_change", "explosive"],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 30, max: 45 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.06,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.5,
    keyMetrics: ["pain_score", "range_of_motion", "strength_load", "steps", "adherence"],
    nonNegotiables: ["Quad isometrics daily — the fastest pain reducer", "Strengthen glutes: weak hips overload the knee", "Progress load before you progress impact"],
    cautions: ["Knee locking, giving way or true swelling needs imaging, not more exercise", "Avoid deep squats and lunges until pain-free at partial range"],
    successSignals: ["Stairs down without pain", "30-second sit-to-stand test improving"],
    expectedTimeline: "Pain relief in 2-4 weeks; capacity in 8-12 weeks",
  },
  back_pain: {
    id: "back_pain",
    label: "Relieve back pain",
    purpose: "Build a back that tolerates sitting, lifting and daily life without flaring.",
    family: "musculoskeletal",
    mechanism:
      "Chronic low back pain responds to trunk endurance, hip mobility and graded exposure to movement — not rest. Anti-movement core work (planks, bird-dog, dead-bug) builds stiffness where the spine needs it, and walking is one of the best-evidenced treatments.",
    bucketWeights: { rehab_corrective: 9, strength: 6, mobility_flexibility: 7, cardio_steady: 5, mindbody_calm: 4 },
    primaryCategories: ["rehab", "mobility", "walking", "pilates", "yoga", "swimming", "gym_strength"],
    avoidTags: ["spinal_flexion", "deep_twist", "loaded_spine", "high_impact", "jumping", "sustained_forward_bend", "heavy_load"],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 30, max: 45 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.05,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.4,
    keyMetrics: ["pain_score", "stiffness_minutes", "steps", "sleep_quality", "adherence", "mood"],
    nonNegotiables: [
      "Walk daily — short frequent walks beat one long one",
      "Avoid repeated end-range spinal flexion first thing in the morning",
      "Hinge at the hips, not the spine, when lifting",
      "Break up sitting every 30-45 minutes",
    ],
    cautions: [
      "Pain radiating below the knee, numbness, weakness, or bladder/bowel changes — stop and seek care immediately",
      "Bed rest beyond 1-2 days makes back pain worse",
    ],
    successSignals: ["Longer pain-free sitting and standing tolerance", "Fewer flare days", "Confidence bending and lifting"],
    expectedTimeline: "Acute pain settles in 2-6 weeks; capacity builds over 12 weeks",
  },
  neck_shoulder_pain: {
    id: "neck_shoulder_pain",
    label: "Ease neck & shoulder pain",
    purpose: "Undo desk-driven neck and shoulder tension and build upper-back strength.",
    family: "musculoskeletal",
    mechanism:
      "Neck pain from screen work is a tolerance problem: the tissue is under low load for too long. Frequent postural breaks, scapular and deep-neck-flexor strength, and thoracic mobility give the neck more capacity than the day demands.",
    bucketWeights: { rehab_corrective: 9, mobility_flexibility: 7, strength: 5, mindbody_calm: 4, cardio_steady: 3 },
    primaryCategories: ["rehab", "mobility", "yoga", "pilates", "gym_strength", "walking"],
    avoidTags: ["neck_loading", "overhead_reach", "inversion", "shoulder_end_range", "heavy_load", "high_impact"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 25, max: 40 },
    weeklyMinutesTarget: 140,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["pain_score", "range_of_motion", "stiffness_minutes", "stress", "adherence"],
    nonNegotiables: ["A 2-minute reset every hour of screen work", "Chin tucks and scapular retraction daily", "Screen at eye level, elbows supported"],
    cautions: ["Headache with neck pain, arm numbness or weakness needs assessment", "Avoid loaded overhead pressing while symptomatic"],
    successSignals: ["Fewer end-of-day headaches", "Easier head rotation while driving"],
    expectedTimeline: "Noticeable relief in 2-3 weeks",
  },
  bone_density: {
    id: "bone_density",
    label: "Strengthen bones",
    purpose: "Protect against osteopenia and osteoporosis and reduce fracture risk.",
    family: "musculoskeletal",
    mechanism:
      "Bone remodels in response to load and to muscle pull. Progressive resistance training plus weight-bearing impact (scaled to what the skeleton can safely take) is the only intervention that reliably builds bone. Balance training prevents the falls that turn low bone density into fractures.",
    bucketWeights: { strength: 9, balance_coordination: 6, cardio_steady: 4, mobility_flexibility: 4 },
    primaryCategories: ["gym_strength", "walking", "functional", "mobility", "dance"],
    avoidTags: ["spinal_flexion", "deep_twist", "sustained_forward_bend", "fall_risk", "contact_risk"],
    intensityCap: "moderate",
    sessionMinutes: { min: 20, target: 40, max: 60 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.5,
    keyMetrics: ["strength_load", "balance_seconds", "weight", "adherence"],
    nonNegotiables: ["Weight-bearing movement most days", "Progressive resistance twice weekly", "Adequate calcium, vitamin D and protein"],
    cautions: [
      "With diagnosed osteoporosis, avoid loaded forward bending and forceful twisting — vertebral fracture risk",
      "Swimming and cycling are healthy but do not build bone; keep weight-bearing work in the plan",
    ],
    successSignals: ["Stronger lifts", "Single-leg balance beyond 30 seconds", "Improved DEXA at 12-24 months"],
    expectedTimeline: "Bone responds over 6-12 months; strength and balance improve in weeks",
  },
  flexibility: {
    id: "flexibility",
    label: "Improve flexibility",
    purpose: "Move through fuller range with less tightness.",
    family: "musculoskeletal",
    mechanism:
      "Range improves through regular end-range exposure and, more durably, through strength at long muscle lengths. Static stretching after warm tissue and loaded stretching both work; consistency matters more than duration.",
    bucketWeights: { mobility_flexibility: 10, mindbody_calm: 4, strength: 3, active_recovery: 3 },
    primaryCategories: ["yoga", "mobility", "pilates", "recovery"],
    avoidTags: [],
    intensityCap: "light",
    sessionMinutes: { min: 10, target: 25, max: 45 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.2,
    keyMetrics: ["flexibility_reach", "range_of_motion", "adherence", "stiffness_minutes"],
    nonNegotiables: ["Daily practice beats long weekly sessions", "Hold 30-60 seconds, breathe out into the stretch", "Warm up before end-range work"],
    cautions: ["Stretch to tension, never sharp pain", "If you are naturally hypermobile, prioritise strength over more range"],
    successSignals: ["Sit-and-reach improving", "Squatting deeper comfortably"],
    expectedTimeline: "Measurable in 3-4 weeks; lasting in 8-12 weeks",
  },
  mobility: {
    id: "mobility",
    label: "Move better (mobility)",
    purpose: "Own your range of motion with control, not just passive flexibility.",
    family: "musculoskeletal",
    mechanism:
      "Mobility is flexibility you can control. Joint-by-joint active work, end-range strength and controlled articular rotations turn available range into usable range.",
    bucketWeights: { mobility_flexibility: 9, rehab_corrective: 6, strength: 5, balance_coordination: 4 },
    primaryCategories: ["mobility", "yoga", "pilates", "functional", "rehab"],
    avoidTags: [],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 30, max: 45 },
    weeklyMinutesTarget: 160,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.3,
    keyMetrics: ["range_of_motion", "flexibility_reach", "balance_seconds", "adherence"],
    nonNegotiables: ["Move every major joint through full range daily", "Add active holds at end range"],
    cautions: ["Do not force ranges your joint structure does not have"],
    successSignals: ["Deep squat held comfortably", "Overhead reach without arching"],
    expectedTimeline: "4-8 weeks",
  },
  posture: {
    id: "posture",
    label: "Improve posture",
    purpose: "Stand and sit tall without effort, and stop slouch-driven aches.",
    family: "musculoskeletal",
    mechanism:
      "There is no single correct posture — the problem is staying in one position too long with too little strength. The fix is thoracic mobility, posterior-chain and scapular strength, and frequent position changes.",
    bucketWeights: { rehab_corrective: 8, strength: 6, mobility_flexibility: 7, mindbody_calm: 3 },
    primaryCategories: ["mobility", "rehab", "gym_strength", "pilates", "yoga"],
    avoidTags: ["sustained_forward_bend"],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 30, max: 45 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["pain_score", "range_of_motion", "adherence", "stiffness_minutes"],
    nonNegotiables: ["Rows and pulls twice as often as pushes", "Thoracic extension daily", "Change position every 30 minutes"],
    cautions: ["Bracing yourself rigidly upright all day is not the goal — variety is"],
    successSignals: ["Less end-of-day upper-back fatigue", "Photos showing an easier neutral stance"],
    expectedTimeline: "4-8 weeks",
  },
  balance_fall_prevention: {
    id: "balance_fall_prevention",
    label: "Better balance, fewer falls",
    purpose: "Stay steady on your feet and confident on stairs and uneven ground.",
    family: "musculoskeletal",
    mechanism:
      "Falls come from a mix of weak legs, slow reactions and poor balance. Progressive balance challenge, leg strength, and ankle/hip strategy training reduce fall rate substantially — this is one of the strongest effects in all of exercise research.",
    bucketWeights: { balance_coordination: 9, strength: 7, mobility_flexibility: 5, cardio_steady: 4, mindbody_calm: 3 },
    primaryCategories: ["functional", "martial_arts", "gym_strength", "mobility", "walking", "dance"],
    avoidTags: ["high_impact", "jumping", "rapid_direction_change", "contact_risk"],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 30, max: 45 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.5,
    keyMetrics: ["balance_seconds", "strength_load", "steps", "adherence"],
    nonNegotiables: ["Balance work 3+ days a week, always with a support within reach", "Sit-to-stand practice daily", "Well-fitting shoes, clear floors, good lighting"],
    cautions: ["Always train balance beside a wall, rail or chair", "New unsteadiness or dizziness needs medical review"],
    successSignals: ["Single-leg stand over 30 seconds", "5 sit-to-stands under 10 seconds"],
    expectedTimeline: "Improvement in 4-6 weeks; fall-risk reduction at 12+ weeks",
  },
  pelvic_floor: {
    id: "pelvic_floor",
    label: "Pelvic floor strength",
    purpose: "Restore pelvic floor control for continence, core function and comfort.",
    family: "musculoskeletal",
    mechanism:
      "The pelvic floor is part of the deep core system and coordinates with the diaphragm. Training combines relaxation and contraction with breath, then reintroduces load. Impact and heavy straining are added last.",
    bucketWeights: { rehab_corrective: 10, mindbody_calm: 5, mobility_flexibility: 4, strength: 4, cardio_steady: 3 },
    primaryCategories: ["rehab", "pilates", "breathwork", "yoga", "walking"],
    avoidTags: ["high_impact", "jumping", "intra_abdominal_pressure", "valsalva", "heavy_load", "pelvic_floor_load"],
    intensityCap: "light",
    sessionMinutes: { min: 10, target: 25, max: 40 },
    weeklyMinutesTarget: 120,
    progressionRate: 0.04,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["pain_score", "adherence", "range_of_motion"],
    nonNegotiables: ["Learn to fully relax the pelvic floor, not only contract it", "Exhale on effort", "Progress from lying to sitting to standing"],
    cautions: [
      "Heaviness, bulging or leaking during exercise means reduce load and see a pelvic health physiotherapist",
      "Do not do endless Kegels — an over-tight pelvic floor causes its own symptoms",
    ],
    successSignals: ["Less leaking with cough or exercise", "Better core control"],
    expectedTimeline: "6-12 weeks with daily practice",
  },

  /* ------------------------------------------------------------------ *
   * Metabolic
   * ------------------------------------------------------------------ */
  blood_sugar: {
    id: "blood_sugar",
    label: "Control blood sugar",
    purpose: "Improve insulin sensitivity and keep glucose in range.",
    family: "metabolic",
    mechanism:
      "Muscle contraction pulls glucose out of the blood without insulin. A short walk after meals blunts the post-meal spike, and resistance training increases the muscle that stores glucose. Effects on insulin sensitivity fade in 48-72 hours, so frequency beats intensity.",
    bucketWeights: { cardio_steady: 8, strength: 7, cardio_interval: 4, mobility_flexibility: 3, mindbody_calm: 3 },
    primaryCategories: ["walking", "gym_strength", "cycling", "yoga", "swimming"],
    avoidTags: [],
    intensityCap: "moderate",
    sessionMinutes: { min: 20, target: 40, max: 60 },
    weeklyMinutesTarget: 210,
    progressionRate: 0.07,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.5,
    keyMetrics: ["blood_glucose", "weight", "waist", "steps", "active_minutes", "adherence"],
    nonNegotiables: [
      "10-15 minute walk within 30 minutes of each main meal",
      "Never let two days pass without exercise",
      "Resistance training twice weekly",
      "Carry fast-acting carbohydrate if you use insulin or sulfonylureas",
    ],
    cautions: [
      "Check glucose before and after sessions while you learn your response",
      "Do not exercise if glucose is below 90 mg/dL without eating first, or above 250 mg/dL with ketones",
      "Inspect feet daily if you have any neuropathy; choose low-impact shoes",
    ],
    successSignals: ["Lower fasting glucose", "Smaller post-meal spikes", "HbA1c down at 3 months"],
    expectedTimeline: "Glucose response within days; HbA1c at 8-12 weeks",
  },
  blood_pressure: {
    id: "blood_pressure",
    label: "Lower blood pressure",
    purpose: "Bring blood pressure down and keep it there.",
    family: "metabolic",
    mechanism:
      "Aerobic exercise lowers systolic pressure by roughly 5-8 mmHg, and isometric handgrip or wall-sit protocols can match that. Breathwork lowers sympathetic drive. Heavy straining with breath-holding spikes pressure and is avoided.",
    bucketWeights: { cardio_steady: 9, mindbody_calm: 6, strength: 5, mobility_flexibility: 3 },
    primaryCategories: ["walking", "cycling", "swimming", "breathwork", "yoga", "gym_strength"],
    avoidTags: ["valsalva", "breath_retention", "heavy_load", "inversion", "max_heart_rate"],
    intensityCap: "moderate",
    sessionMinutes: { min: 20, target: 40, max: 60 },
    weeklyMinutesTarget: 210,
    progressionRate: 0.06,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.4,
    keyMetrics: ["blood_pressure", "resting_hr", "weight", "waist", "stress", "adherence"],
    nonNegotiables: ["Aerobic work on most days", "Never hold your breath under load — exhale on effort", "Slow breathing practice daily", "Reduce salt"],
    cautions: [
      "Do not exercise if resting BP is above 180/110 — get it treated first",
      "Skip inversions and heavy overhead loading",
      "Dizziness on standing after exercise: cool down for longer",
    ],
    successSignals: ["Home readings trending down", "Lower resting heart rate"],
    expectedTimeline: "4-8 weeks of consistent aerobic work",
  },
  cholesterol: {
    id: "cholesterol",
    label: "Improve cholesterol",
    purpose: "Raise HDL, lower triglycerides and improve your lipid profile.",
    family: "metabolic",
    mechanism:
      "Aerobic volume is the main driver of triglyceride reduction and HDL improvement; total weekly minutes matter more than intensity. Losing visceral fat compounds the effect.",
    bucketWeights: { cardio_steady: 9, strength: 5, cardio_interval: 4, mobility_flexibility: 3 },
    primaryCategories: ["walking", "running", "cycling", "swimming", "gym_strength"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 25, target: 45, max: 70 },
    weeklyMinutesTarget: 250,
    progressionRate: 0.08,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.4,
    keyMetrics: ["weight", "waist", "active_minutes", "steps", "adherence"],
    nonNegotiables: ["Accumulate 250+ minutes of aerobic work weekly", "Strength twice a week", "Soluble fibre and fewer refined carbohydrates"],
    cautions: ["Lipids respond slowly — retest no sooner than 12 weeks"],
    successSignals: ["Triglycerides down, HDL up at 3 months"],
    expectedTimeline: "12 weeks",
  },
  pcos_hormonal: {
    id: "pcos_hormonal",
    label: "PCOS & hormonal balance",
    purpose: "Improve insulin sensitivity, cycle regularity and PCOS symptoms.",
    family: "metabolic",
    mechanism:
      "PCOS is driven largely by insulin resistance. Resistance training plus moderate cardio improves insulin sensitivity and androgen profile; excessive high-intensity volume with under-eating can worsen cycle disruption, so intensity is kept sustainable and stress management is part of the plan.",
    bucketWeights: { strength: 8, cardio_steady: 6, mindbody_calm: 5, cardio_interval: 3, mobility_flexibility: 4 },
    primaryCategories: ["gym_strength", "walking", "yoga", "cycling", "swimming", "breathwork"],
    avoidTags: [],
    intensityCap: "moderate",
    sessionMinutes: { min: 25, target: 40, max: 60 },
    weeklyMinutesTarget: 200,
    progressionRate: 0.07,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.6,
    keyMetrics: ["weight", "waist", "blood_glucose", "mood", "sleep_quality", "adherence", "stress"],
    nonNegotiables: ["Resistance training 2-3 times weekly", "Walk daily", "Protect sleep and manage stress", "Do not under-eat while over-training"],
    cautions: ["Very low calories plus heavy training can stop cycles altogether", "5-10% weight loss often restores ovulation — that is the target, not extremes"],
    successSignals: ["More regular cycles", "Lower fasting insulin", "Better energy and mood"],
    expectedTimeline: "12-16 weeks",
  },
  thyroid_support: {
    id: "thyroid_support",
    label: "Thyroid support",
    purpose: "Work with a thyroid condition instead of against it.",
    family: "metabolic",
    mechanism:
      "In hypothyroidism, fatigue and slower recovery mean starting low and building gradually; resistance training helps offset the metabolic slowdown. In hyperthyroidism, intensity must stay low until the condition is medically controlled.",
    bucketWeights: { strength: 7, cardio_steady: 6, mindbody_calm: 5, mobility_flexibility: 4, active_recovery: 3 },
    primaryCategories: ["walking", "gym_strength", "yoga", "swimming", "breathwork"],
    avoidTags: ["max_heart_rate"],
    intensityCap: "moderate",
    sessionMinutes: { min: 20, target: 35, max: 55 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.05,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.5,
    keyMetrics: ["weight", "energy", "resting_hr", "sleep_quality", "adherence", "mood"],
    nonNegotiables: ["Start at half the volume you think you can do", "Take medication consistently, as prescribed", "Track energy, not just minutes"],
    cautions: ["Untreated hyperthyroidism: avoid vigorous exercise until controlled", "Unusual resting heart rate or palpitations need review"],
    successSignals: ["Steadier energy", "Weight responding to the plan"],
    expectedTimeline: "8-12 weeks once thyroid levels are stable",
  },
  fatty_liver: {
    id: "fatty_liver",
    label: "Fatty liver improvement",
    purpose: "Reduce liver fat and improve liver enzymes.",
    family: "metabolic",
    mechanism:
      "Liver fat is highly responsive to exercise, even before weight changes. A 7-10% body-weight reduction can reverse steatosis; aerobic and resistance training both reduce liver fat independently.",
    bucketWeights: { cardio_steady: 8, strength: 7, cardio_interval: 4, mobility_flexibility: 3 },
    primaryCategories: ["walking", "cycling", "gym_strength", "swimming", "running"],
    avoidTags: [],
    intensityCap: "moderate",
    sessionMinutes: { min: 25, target: 45, max: 65 },
    weeklyMinutesTarget: 240,
    progressionRate: 0.08,
    energyBalance: "deficit",
    proteinGPerKg: 1.6,
    keyMetrics: ["weight", "waist", "active_minutes", "adherence"],
    nonNegotiables: ["Aim for 7-10% body weight reduction", "Cut sugary drinks and alcohol entirely", "Exercise 5 days a week"],
    cautions: ["Rapid crash dieting can worsen liver inflammation"],
    successSignals: ["Waist and weight down", "ALT/AST improving at 3-6 months"],
    expectedTimeline: "12-24 weeks",
  },

  /* ------------------------------------------------------------------ *
   * Cardio-respiratory
   * ------------------------------------------------------------------ */
  heart_health: {
    id: "heart_health",
    label: "Heart health",
    purpose: "Build a stronger, more efficient cardiovascular system.",
    family: "cardio_respiratory",
    mechanism:
      "Cardiorespiratory fitness is the single strongest predictor of long-term health. Mostly-easy aerobic work builds the base, a small dose of harder work lifts peak capacity, and strength training supports both.",
    bucketWeights: { cardio_steady: 9, cardio_interval: 5, strength: 5, mobility_flexibility: 3, mindbody_calm: 3 },
    primaryCategories: ["walking", "running", "cycling", "swimming", "rowing", "gym_strength"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 25, target: 45, max: 70 },
    weeklyMinutesTarget: 220,
    progressionRate: 0.08,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["resting_hr", "hrv", "active_minutes", "blood_pressure", "distance", "adherence"],
    nonNegotiables: ["80% of cardio easy enough to hold a conversation", "One harder session a week once your base is built", "Strength twice weekly"],
    cautions: ["Chest pain, unusual breathlessness or palpitations — stop and seek care", "Progress volume before intensity"],
    successSignals: ["Resting heart rate down 3-8 bpm", "Same pace at a lower heart rate"],
    expectedTimeline: "6-12 weeks",
  },
  stamina: {
    id: "stamina",
    label: "Build stamina",
    purpose: "Stop getting winded — climb stairs and keep up without gasping.",
    family: "cardio_respiratory",
    mechanism:
      "Endurance comes from consistent aerobic volume that grows mitochondria and capillaries, plus intervals that raise your ceiling. Starting with walk-run or interval-style progression makes it achievable from any baseline.",
    bucketWeights: { cardio_steady: 9, cardio_interval: 6, strength: 4, mobility_flexibility: 3 },
    primaryCategories: ["walking", "running", "cycling", "swimming", "rowing", "hiit"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 20, target: 40, max: 70 },
    weeklyMinutesTarget: 200,
    progressionRate: 0.1,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["active_minutes", "distance", "pace", "resting_hr", "rpe", "adherence"],
    nonNegotiables: ["Increase total time before speed", "Keep most sessions conversational", "One long easy session weekly"],
    cautions: ["The 10% rule: do not add more than 10% weekly volume", "Persistent heavy legs means you need a lighter week"],
    successSignals: ["Same route feeling easier", "Stairs without breathlessness"],
    expectedTimeline: "4-8 weeks",
  },
  breathing_capacity: {
    id: "breathing_capacity",
    label: "Better breathing",
    purpose: "Breathe more efficiently, with less breathlessness during effort.",
    family: "cardio_respiratory",
    mechanism:
      "Breathing retraining lowers over-breathing, improves diaphragm use and CO2 tolerance. Combined with graded aerobic work, it reduces the sensation of breathlessness even before lung function changes.",
    bucketWeights: { mindbody_calm: 8, cardio_steady: 7, mobility_flexibility: 5, strength: 3 },
    primaryCategories: ["breathwork", "walking", "swimming", "yoga", "cycling"],
    avoidTags: ["breath_retention", "pollen_exposure", "air_pollution_exposure", "cold_exposure"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 50 },
    weeklyMinutesTarget: 170,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.3,
    keyMetrics: ["breath_hold", "active_minutes", "rpe", "energy", "adherence"],
    nonNegotiables: ["Nose-breathe at easy intensities", "Daily diaphragmatic breathing", "Warm up for 10 minutes before harder efforts"],
    cautions: ["Keep reliever inhaler with you if asthmatic", "Avoid outdoor sessions on high-pollution or high-pollen days"],
    successSignals: ["Longer comfortable breath hold", "Less breathlessness at the same pace"],
    expectedTimeline: "3-6 weeks",
  },
  immunity: {
    id: "immunity",
    label: "Stronger immunity",
    purpose: "Get sick less often and recover faster.",
    family: "cardio_respiratory",
    mechanism:
      "Moderate regular exercise improves immune surveillance; very high training loads with poor sleep suppress it. The plan sits deliberately in the moderate band, with sleep and recovery treated as training.",
    bucketWeights: { cardio_steady: 7, strength: 5, mindbody_calm: 5, mobility_flexibility: 4, active_recovery: 4 },
    primaryCategories: ["walking", "yoga", "gym_strength", "breathwork", "cycling"],
    avoidTags: ["max_heart_rate", "long_duration"],
    intensityCap: "moderate",
    sessionMinutes: { min: 20, target: 35, max: 55 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["sleep_hours", "energy", "active_minutes", "stress", "adherence"],
    nonNegotiables: ["Sleep 7-8 hours", "Daily outdoor light exposure", "Do not train hard when run down"],
    cautions: ["Fever, body aches or chest symptoms: rest completely until 24 hours symptom-free"],
    successSignals: ["Fewer sick days", "Faster recovery from minor illness"],
    expectedTimeline: "Ongoing",
  },

  /* ------------------------------------------------------------------ *
   * Mental wellbeing
   * ------------------------------------------------------------------ */
  stress_calm: {
    id: "stress_calm",
    label: "Feel calmer",
    purpose: "Lower daily stress and end the day settled rather than wired.",
    family: "mental_wellbeing",
    mechanism:
      "Slow breathing with a long exhale shifts you into parasympathetic dominance within minutes. Rhythmic moderate movement burns off circulating stress hormones, and yoga and meditation raise the threshold at which stress registers at all. Very hard training late in the day does the opposite.",
    bucketWeights: { mindbody_calm: 10, cardio_steady: 6, mobility_flexibility: 6, active_recovery: 4, strength: 3 },
    primaryCategories: ["breathwork", "yoga", "meditation", "walking", "martial_arts", "recovery"],
    avoidTags: ["max_heart_rate", "vigorous_intensity", "explosive"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 50 },
    weeklyMinutesTarget: 170,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.3,
    keyMetrics: ["stress", "mood", "sleep_quality", "hrv", "resting_hr", "adherence"],
    nonNegotiables: [
      "5 minutes of slow breathing every day, non-negotiable",
      "Get outside in daylight — walking outdoors beats the same walk on a treadmill for mood",
      "Keep hard sessions at least 3 hours before bed",
      "One screen-free wind-down block each evening",
    ],
    cautions: [
      "Fast forceful breathing (kapalbhati, bhastrika) can provoke anxiety and is left out until you are settled",
      "If low mood or anxiety is severe or persistent, exercise supports treatment but does not replace it",
    ],
    successSignals: ["Falling asleep faster", "Fewer tension headaches", "Reacting less to small annoyances"],
    expectedTimeline: "Single sessions help the same day; durable change in 3-4 weeks",
  },
  anxiety_relief: {
    id: "anxiety_relief",
    label: "Reduce anxiety",
    purpose: "Turn down baseline anxiety and handle anxious moments better.",
    family: "mental_wellbeing",
    mechanism:
      "Aerobic exercise reduces anxiety sensitivity by repeatedly exposing you to raised heart rate and breathing in a safe context. Extended-exhale breathing gives an immediate off-switch, and yoga reduces both physical and cognitive symptoms.",
    bucketWeights: { mindbody_calm: 9, cardio_steady: 7, mobility_flexibility: 5, strength: 4, active_recovery: 3 },
    primaryCategories: ["walking", "breathwork", "yoga", "running", "meditation", "swimming"],
    avoidTags: ["breath_retention", "max_heart_rate"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 50 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.3,
    keyMetrics: ["mood", "stress", "sleep_quality", "resting_hr", "adherence", "energy"],
    nonNegotiables: ["Move daily, even 10 minutes", "Practise long-exhale breathing before it is needed, not only during a spike", "Limit caffeine, especially after noon"],
    cautions: ["Rapid breathing drills can trigger panic — use slow paced breathing instead", "Seek professional support for panic attacks or persistent anxiety"],
    successSignals: ["Lower baseline tension", "Quicker recovery from anxious episodes"],
    expectedTimeline: "Immediate acute relief; 4-6 weeks for baseline change",
  },
  mood_depression: {
    id: "mood_depression",
    label: "Lift mood",
    purpose: "Use movement to improve mood, motivation and outlook.",
    family: "mental_wellbeing",
    mechanism:
      "Exercise has a clinically meaningful antidepressant effect, strongest for supervised or social aerobic and resistance training in daylight. The plan removes friction with very small minimum doses on hard days, because starting is the whole battle.",
    bucketWeights: { cardio_steady: 8, strength: 6, mindbody_calm: 5, sport_play: 4, mobility_flexibility: 3 },
    primaryCategories: ["walking", "running", "gym_strength", "dance", "sports", "yoga"],
    avoidTags: [],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 50 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["mood", "energy", "sleep_hours", "active_minutes", "adherence", "stress"],
    nonNegotiables: [
      "Morning daylight within an hour of waking",
      "Define a 5-minute minimum version of every session for low days",
      "Prefer social or outdoor options where possible",
    ],
    cautions: ["Exercise complements, never replaces, treatment", "If you have thoughts of self-harm, contact a professional or crisis line immediately"],
    successSignals: ["More days started with movement", "Mood rating trending up over weeks"],
    expectedTimeline: "2-4 weeks",
  },
  sleep_quality: {
    id: "sleep_quality",
    label: "Sleep better",
    purpose: "Fall asleep faster, wake less, and feel rested.",
    family: "mental_wellbeing",
    mechanism:
      "Daytime activity and morning light strengthen circadian signalling, and exercise increases deep sleep. Evening intensity, on the other hand, delays sleep onset — so hard work is scheduled early and the evening gets wind-down work only.",
    bucketWeights: { cardio_steady: 7, mindbody_calm: 8, mobility_flexibility: 5, strength: 4, active_recovery: 4 },
    primaryCategories: ["walking", "yoga", "breathwork", "meditation", "cycling", "recovery"],
    avoidTags: ["max_heart_rate", "vigorous_intensity"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 50 },
    weeklyMinutesTarget: 170,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.3,
    keyMetrics: ["sleep_hours", "sleep_quality", "mood", "energy", "resting_hr", "adherence"],
    nonNegotiables: [
      "Same wake time every day, weekends included",
      "Daylight within an hour of waking",
      "No vigorous exercise within 3 hours of bed",
      "Caffeine cut-off 8 hours before bed",
    ],
    cautions: ["Loud snoring with daytime sleepiness may be sleep apnoea — get it investigated"],
    successSignals: ["Falling asleep within 20 minutes", "Fewer night wakings", "Waking before the alarm"],
    expectedTimeline: "2-4 weeks",
  },
  energy_fatigue: {
    id: "energy_fatigue",
    label: "More energy, less fatigue",
    purpose: "Break the tired-so-I-rest-so-I-get-more-tired cycle.",
    family: "mental_wellbeing",
    mechanism:
      "Deconditioning itself causes fatigue. Low-dose, highly consistent activity — paced so that you never crash the next day — rebuilds capacity. Pacing, not pushing, is the operating principle.",
    bucketWeights: { cardio_steady: 6, mobility_flexibility: 6, mindbody_calm: 6, strength: 5, active_recovery: 5 },
    primaryCategories: ["walking", "yoga", "mobility", "breathwork", "gym_strength", "swimming"],
    avoidTags: ["max_heart_rate", "long_duration", "vigorous_intensity"],
    intensityCap: "light",
    sessionMinutes: { min: 5, target: 20, max: 35 },
    weeklyMinutesTarget: 120,
    progressionRate: 0.04,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["energy", "sleep_hours", "active_minutes", "mood", "rpe", "adherence"],
    nonNegotiables: [
      "Stop each session while you still have something left",
      "Split activity into short bouts across the day",
      "Consistency over intensity, always",
    ],
    cautions: [
      "If effort reliably makes you worse for 24+ hours afterwards, that is post-exertional malaise — reduce the dose and get assessed",
      "Persistent unexplained fatigue deserves blood work (thyroid, iron, B12, glucose)",
    ],
    successSignals: ["No crash the day after", "Slowly rising daily step count"],
    expectedTimeline: "4-8 weeks of patient progression",
  },
  focus_cognition: {
    id: "focus_cognition",
    label: "Sharper focus",
    purpose: "Improve concentration, memory and mental clarity.",
    family: "mental_wellbeing",
    mechanism:
      "A single bout of moderate aerobic exercise improves executive function for hours afterwards. Coordination-heavy activity and meditation add structural benefits. Movement breaks during deep work outperform pushing through.",
    bucketWeights: { cardio_steady: 7, mindbody_calm: 6, balance_coordination: 5, strength: 4, mobility_flexibility: 4 },
    primaryCategories: ["walking", "running", "meditation", "dance", "martial_arts", "sports"],
    avoidTags: [],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 45 },
    weeklyMinutesTarget: 170,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["mood", "energy", "sleep_quality", "active_minutes", "adherence"],
    nonNegotiables: ["Move before your most demanding work block", "A 5-minute walk every 60-90 minutes of desk work", "Learn something coordination-heavy"],
    cautions: ["Exhaustive training impairs focus for the rest of the day"],
    successSignals: ["Longer productive blocks", "Less afternoon fog"],
    expectedTimeline: "Same-day effect; cumulative over 6-8 weeks",
  },
  addiction_recovery: {
    id: "addiction_recovery",
    label: "Recovery support",
    purpose: "Use structured activity to support recovery from a habit or substance.",
    family: "mental_wellbeing",
    mechanism:
      "Exercise reduces craving intensity, restores dopamine sensitivity, fills high-risk time slots and rebuilds self-efficacy. Group or outdoor formats add the social scaffolding that predicts staying the course.",
    bucketWeights: { cardio_steady: 7, strength: 6, mindbody_calm: 6, sport_play: 4, mobility_flexibility: 3 },
    primaryCategories: ["walking", "gym_strength", "running", "yoga", "sports", "martial_arts"],
    avoidTags: [],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 35, max: 55 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.06,
    energyBalance: "maintenance",
    proteinGPerKg: 1.5,
    keyMetrics: ["mood", "stress", "sleep_quality", "adherence", "energy", "active_minutes"],
    nonNegotiables: ["Schedule sessions in your highest-risk time window", "Prefer group settings", "Never skip two planned sessions in a row"],
    cautions: ["Watch for swapping one compulsion for another — rest days are part of the plan", "Keep your clinical or peer support in place alongside this"],
    successSignals: ["Craving intensity lower after sessions", "Structure holding through difficult weeks"],
    expectedTimeline: "Immediate craving relief; structural benefit over months",
  },

  /* ------------------------------------------------------------------ *
   * Life stage
   * ------------------------------------------------------------------ */
  prenatal: {
    id: "prenatal",
    label: "Pregnancy fitness",
    purpose: "Stay strong and comfortable through pregnancy, safely.",
    family: "life_stage",
    mechanism:
      "Exercise in pregnancy lowers gestational diabetes and pre-eclampsia risk, eases back pain and improves recovery. Guidance is 150 minutes of moderate activity weekly, avoiding supine positions after the first trimester, contact and fall risk, overheating, and breath-holding.",
    bucketWeights: { cardio_steady: 7, rehab_corrective: 7, strength: 5, mobility_flexibility: 5, mindbody_calm: 5 },
    primaryCategories: ["walking", "swimming", "yoga", "pilates", "rehab", "breathwork"],
    avoidTags: [
      "high_impact", "jumping", "contact_risk", "fall_risk", "supine_position", "prone_position",
      "inversion", "deep_twist", "breath_retention", "valsalva", "heat_exposure", "intra_abdominal_pressure",
      "max_heart_rate", "spinal_flexion", "rapid_direction_change",
    ],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 45 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.0,
    energyBalance: "maintenance",
    proteinGPerKg: 1.6,
    keyMetrics: ["active_minutes", "energy", "pain_score", "sleep_quality", "mood", "adherence"],
    nonNegotiables: [
      "Talk test only — you should be able to hold a conversation throughout",
      "No lying flat on your back for exercise after week 16",
      "Hydrate well and avoid getting overheated",
      "Pelvic floor and breathing work daily",
    ],
    cautions: [
      "Stop immediately and contact your doctor for bleeding, fluid leakage, regular painful contractions, dizziness, chest pain, calf pain or swelling, or reduced fetal movement",
      "Clear your exercise plan with your obstetrician, especially with any pregnancy complication",
      "This is not the time to chase new fitness records",
    ],
    successSignals: ["Comfortable daily movement", "Manageable back and pelvic discomfort"],
    expectedTimeline: "Maintain throughout, adapting each trimester",
  },
  postpartum: {
    id: "postpartum",
    label: "Postpartum recovery",
    purpose: "Rebuild core, pelvic floor and whole-body strength after birth.",
    family: "life_stage",
    mechanism:
      "Recovery is sequenced: breathing and pelvic floor first, then deep core and glutes, then load, then impact. Returning to running or jumping before the pelvic floor can handle it is the main cause of long-term problems.",
    bucketWeights: { rehab_corrective: 10, mindbody_calm: 5, strength: 5, mobility_flexibility: 5, cardio_steady: 4 },
    primaryCategories: ["rehab", "pilates", "walking", "breathwork", "yoga", "gym_strength"],
    avoidTags: ["high_impact", "jumping", "intra_abdominal_pressure", "valsalva", "spinal_flexion", "heavy_load", "pelvic_floor_load", "running_gait"],
    intensityCap: "light",
    sessionMinutes: { min: 10, target: 25, max: 40 },
    weeklyMinutesTarget: 130,
    progressionRate: 0.04,
    energyBalance: "maintenance",
    proteinGPerKg: 1.6,
    keyMetrics: ["pain_score", "energy", "sleep_hours", "mood", "adherence", "active_minutes"],
    nonNegotiables: [
      "Breath and pelvic floor before anything else",
      "No running or jumping before 12 weeks, and only once pain-free and leak-free",
      "Exhale on every effort",
      "Get a pelvic health physiotherapy assessment if you can",
    ],
    cautions: [
      "Heavy bleeding, pain, heaviness or leaking means stop and get assessed",
      "Caesarean recovery needs longer — no core loading until cleared",
      "Doming along the midline during core work means the exercise is too advanced",
    ],
    successSignals: ["No leaking with movement", "Flat, controlled core engagement", "Confidence carrying your baby"],
    expectedTimeline: "12-24 weeks, and that is normal",
  },
  menopause_support: {
    id: "menopause_support",
    label: "Menopause support",
    purpose: "Protect bone, muscle and mood through peri- and post-menopause.",
    family: "life_stage",
    mechanism:
      "Falling oestrogen accelerates bone and muscle loss and shifts fat centrally. Resistance training plus weight-bearing impact protects bone and muscle; moderate cardio and cooling strategies help vasomotor symptoms and sleep.",
    bucketWeights: { strength: 9, cardio_steady: 6, balance_coordination: 4, mindbody_calm: 5, mobility_flexibility: 4 },
    primaryCategories: ["gym_strength", "walking", "yoga", "functional", "swimming", "dance"],
    avoidTags: ["heat_exposure"],
    intensityCap: "vigorous",
    sessionMinutes: { min: 25, target: 40, max: 60 },
    weeklyMinutesTarget: 200,
    progressionRate: 0.07,
    energyBalance: "maintenance",
    proteinGPerKg: 1.7,
    keyMetrics: ["strength_load", "weight", "waist", "sleep_quality", "mood", "adherence", "balance_seconds"],
    nonNegotiables: ["Resistance training 2-3 times weekly — this is the priority", "Protein 1.6-2.0 g/kg", "Weight-bearing movement for bone", "Cool environment for evening sessions"],
    cautions: ["Hot yoga and midday outdoor heat can worsen hot flushes", "Joint aches are common — reduce impact, do not stop loading"],
    successSignals: ["Strength up", "Fewer disrupted nights", "Waist stable"],
    expectedTimeline: "8-12 weeks for strength and sleep; bone over a year",
  },
  senior_functional: {
    id: "senior_functional",
    label: "Stay independent (55+)",
    purpose: "Keep the strength, balance and stamina that daily independence needs.",
    family: "life_stage",
    mechanism:
      "After 50, muscle and power decline faster than aerobic fitness, and power is what gets you off a chair or out of the way of a fall. Strength, balance and functional patterns are prioritised, with easy cardio for the heart.",
    bucketWeights: { strength: 8, balance_coordination: 8, cardio_steady: 6, mobility_flexibility: 6, active_recovery: 3 },
    primaryCategories: ["functional", "gym_strength", "walking", "mobility", "martial_arts", "swimming"],
    avoidTags: ["high_impact", "jumping", "contact_risk", "rapid_direction_change", "max_heart_rate", "fall_risk"],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 35, max: 50 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.6,
    keyMetrics: ["balance_seconds", "strength_load", "steps", "adherence", "energy", "pain_score"],
    nonNegotiables: [
      "Strength twice weekly — this protects independence more than anything else",
      "Balance practice most days, always near support",
      "Protein at 1.6 g/kg, spread across meals",
      "Stand up and move every 30 minutes",
    ],
    cautions: ["Progress slowly and hold each level until it feels easy", "New dizziness, chest symptoms or falls need medical review"],
    successSignals: ["Standing from a chair without hands", "Carrying shopping comfortably", "Steadier walking"],
    expectedTimeline: "6-12 weeks for noticeable function",
  },
  teen_fitness: {
    id: "teen_fitness",
    label: "Teen fitness",
    purpose: "Build lifelong movement skill, strength and confidence.",
    family: "life_stage",
    mechanism:
      "Adolescence is the best window for motor skill and bone development. Emphasis goes on varied play, technique-first strength and enjoyment rather than adult-style calorie-focused training.",
    bucketWeights: { sport_play: 8, strength: 6, cardio_steady: 5, balance_coordination: 5, mobility_flexibility: 4 },
    primaryCategories: ["sports", "functional", "running", "gym_strength", "dance", "martial_arts"],
    avoidTags: ["heavy_load", "max_heart_rate"],
    intensityCap: "vigorous",
    sessionMinutes: { min: 30, target: 60, max: 90 },
    weeklyMinutesTarget: 420,
    progressionRate: 0.08,
    energyBalance: "maintenance",
    proteinGPerKg: 1.5,
    keyMetrics: ["active_minutes", "adherence", "mood", "sleep_hours", "strength_load"],
    nonNegotiables: ["60 minutes of activity most days", "Technique before load", "Play sports you actually enjoy", "Sleep 8-10 hours"],
    cautions: ["Avoid maximal lifting and adult training volumes during growth spurts", "Growth-plate pain at knees or heels needs rest and assessment"],
    successSignals: ["Skill improving", "Enjoying training", "Good energy at school"],
    expectedTimeline: "Ongoing development",
  },
  desk_job_reset: {
    id: "desk_job_reset",
    label: "Undo desk-job damage",
    purpose: "Counteract 8+ hours of sitting on hips, back, neck and metabolism.",
    family: "life_stage",
    mechanism:
      "Sitting time carries risk independently of exercise, so the plan attacks both: frequent micro-breaks through the workday, plus hip/thoracic mobility and posterior-chain strength to reverse the shortened positions.",
    bucketWeights: { mobility_flexibility: 8, strength: 6, cardio_steady: 6, rehab_corrective: 6, mindbody_calm: 3 },
    primaryCategories: ["mobility", "walking", "gym_strength", "rehab", "yoga", "cycling"],
    avoidTags: ["sustained_forward_bend"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 50 },
    weeklyMinutesTarget: 180,
    progressionRate: 0.07,
    energyBalance: "mild_deficit",
    proteinGPerKg: 1.4,
    keyMetrics: ["steps", "active_minutes", "pain_score", "stiffness_minutes", "energy", "adherence"],
    nonNegotiables: [
      "Stand and move for 2-3 minutes every 30-45 minutes",
      "Hip flexor and thoracic mobility daily",
      "Walk during at least one call a day",
      "8,000+ steps",
    ],
    cautions: ["A single evening workout does not offset a fully sedentary day — the breaks matter"],
    successSignals: ["Less stiffness at 5pm", "Step count up", "Fewer neck headaches"],
    expectedTimeline: "2-4 weeks",
  },

  /* ------------------------------------------------------------------ *
   * Performance
   * ------------------------------------------------------------------ */
  strength_performance: {
    id: "strength_performance",
    label: "Get stronger",
    purpose: "Add real strength to the main lifts and everyday tasks.",
    family: "performance",
    mechanism:
      "Strength is a skill plus tissue capacity. Heavier loads at lower reps with full recovery train the nervous system; accessory work fills weak links; mobility keeps positions available.",
    bucketWeights: { strength: 10, mobility_flexibility: 4, cardio_steady: 3, active_recovery: 2 },
    primaryCategories: ["gym_strength", "functional", "mobility"],
    avoidTags: [],
    intensityCap: "maximal",
    sessionMinutes: { min: 35, target: 60, max: 90 },
    weeklyMinutesTarget: 210,
    progressionRate: 0.07,
    energyBalance: "mild_surplus",
    proteinGPerKg: 1.8,
    keyMetrics: ["strength_load", "rpe", "weight", "adherence"],
    nonNegotiables: ["Log every set", "Rest 2-3 minutes between heavy sets", "Never trade technique for load"],
    cautions: ["Exhale on effort — do not hold your breath under heavy load", "Deload every 4-6 weeks"],
    successSignals: ["Lifts up 5-10% in 8 weeks"],
    expectedTimeline: "8-12 weeks per meaningful jump",
  },
  endurance_event: {
    id: "endurance_event",
    label: "Train for an event",
    purpose: "Get ready for a 5K, 10K, half marathon, ride or swim.",
    family: "performance",
    mechanism:
      "Event readiness is built on a large easy aerobic base, one weekly long session, a small dose of race-pace work, and strength work to keep tissues durable. Volume rises gradually with planned easy weeks.",
    bucketWeights: { cardio_steady: 10, cardio_interval: 5, strength: 5, mobility_flexibility: 4, active_recovery: 3 },
    primaryCategories: ["running", "cycling", "swimming", "rowing", "gym_strength"],
    avoidTags: [],
    intensityCap: "vigorous",
    sessionMinutes: { min: 30, target: 55, max: 120 },
    weeklyMinutesTarget: 300,
    progressionRate: 0.1,
    energyBalance: "maintenance",
    proteinGPerKg: 1.6,
    keyMetrics: ["distance", "pace", "active_minutes", "resting_hr", "rpe", "adherence"],
    nonNegotiables: ["One long session weekly", "80% easy, 20% hard", "Two strength sessions to stay injury-free", "Every fourth week easier"],
    cautions: ["The 10% rule prevents most overuse injuries", "Niggles that change your gait mean stop, not push"],
    successSignals: ["Long session distance climbing", "Race pace at lower effort"],
    expectedTimeline: "8-16 weeks depending on the event",
  },
  sports_performance: {
    id: "sports_performance",
    label: "Play your sport better",
    purpose: "Improve the fitness, power and durability your sport demands.",
    family: "performance",
    mechanism:
      "Sport performance needs repeat-sprint ability, power, change-of-direction strength and robust tissues. Strength and plyometrics build the engine, sport practice sharpens the skill, and mobility work keeps you available to play.",
    bucketWeights: { sport_play: 8, strength: 7, cardio_interval: 6, balance_coordination: 5, mobility_flexibility: 4 },
    primaryCategories: ["sports", "gym_strength", "hiit", "running", "mobility"],
    avoidTags: [],
    intensityCap: "maximal",
    sessionMinutes: { min: 30, target: 60, max: 100 },
    weeklyMinutesTarget: 280,
    progressionRate: 0.09,
    energyBalance: "maintenance",
    proteinGPerKg: 1.7,
    keyMetrics: ["strength_load", "active_minutes", "rpe", "pain_score", "adherence"],
    nonNegotiables: ["Warm up properly before every session — most sport injuries happen cold", "Strength twice weekly", "One genuinely easy day after match day"],
    cautions: ["Do not add hard conditioning the day before competition", "Any joint instability needs assessment before returning"],
    successSignals: ["Lasting a full match", "Faster recovery between efforts"],
    expectedTimeline: "6-12 weeks",
  },
  explosive_power: {
    id: "explosive_power",
    label: "Build speed & power",
    purpose: "Jump higher, sprint faster, move more explosively.",
    family: "performance",
    mechanism:
      "Power is force times velocity. Heavy strength work raises the force ceiling, and low-volume high-quality plyometrics and sprints train the rate of force development. Quality over quantity: every rep is maximal and fully recovered.",
    bucketWeights: { strength: 8, cardio_interval: 6, balance_coordination: 5, mobility_flexibility: 4 },
    primaryCategories: ["gym_strength", "hiit", "running", "sports", "mobility"],
    avoidTags: [],
    intensityCap: "maximal",
    sessionMinutes: { min: 30, target: 50, max: 75 },
    weeklyMinutesTarget: 200,
    progressionRate: 0.07,
    energyBalance: "maintenance",
    proteinGPerKg: 1.7,
    keyMetrics: ["strength_load", "rpe", "adherence", "pain_score"],
    nonNegotiables: ["Power work first in the session, when fresh", "Full recovery between explosive sets", "Land softly — absorb before you produce"],
    cautions: ["Plyometrics need a strength base first — build squats before jumps", "Never do explosive work on a painful joint"],
    successSignals: ["Higher jump", "Faster short sprints"],
    expectedTimeline: "6-10 weeks",
  },

  /* ------------------------------------------------------------------ *
   * Recovery & rehab
   * ------------------------------------------------------------------ */
  injury_rehab: {
    id: "injury_rehab",
    label: "Recover from injury",
    purpose: "Return to full function after an injury, without re-injury.",
    family: "recovery_rehab",
    mechanism:
      "Tissue heals along a predictable timeline and adapts to graded load. Rehab restores range, then capacity, then speed and impact. Isometrics reduce pain early; the unaffected body keeps training throughout to preserve fitness.",
    bucketWeights: { rehab_corrective: 10, mobility_flexibility: 6, strength: 5, cardio_steady: 4, balance_coordination: 4 },
    primaryCategories: ["rehab", "mobility", "swimming", "gym_strength", "pilates", "walking"],
    avoidTags: ["high_impact", "jumping", "explosive", "rapid_direction_change", "contact_risk", "heavy_load"],
    intensityCap: "light",
    sessionMinutes: { min: 10, target: 25, max: 40 },
    weeklyMinutesTarget: 140,
    progressionRate: 0.04,
    energyBalance: "maintenance",
    proteinGPerKg: 1.6,
    keyMetrics: ["pain_score", "range_of_motion", "strength_load", "adherence", "stiffness_minutes"],
    nonNegotiables: [
      "Follow your physiotherapist's programme where you have one — this plan complements it",
      "Pain during exercise up to 3/10 is acceptable; it must settle within 24 hours",
      "Keep training everything that is not injured",
      "Restore full range before adding load, and load before speed",
    ],
    cautions: ["Increasing pain, swelling or loss of range means step back a stage", "Do not test the injury with the movement that caused it until cleared"],
    successSignals: ["Full pain-free range", "Symmetrical strength", "Confidence in the movement"],
    expectedTimeline: "6 weeks to 6 months depending on tissue",
  },
  post_surgery: {
    id: "post_surgery",
    label: "Post-surgery return",
    purpose: "Rebuild safely after an operation, in the right order.",
    family: "recovery_rehab",
    mechanism:
      "Early movement prevents stiffness and clots, but healing tissue and incisions dictate the ceiling. Progression is strictly clinician-led; this plan supplies the general conditioning around your surgical protocol.",
    bucketWeights: { rehab_corrective: 10, mobility_flexibility: 6, cardio_steady: 4, strength: 4, active_recovery: 4 },
    primaryCategories: ["rehab", "walking", "mobility", "breathwork", "pilates"],
    avoidTags: ["heavy_load", "high_impact", "jumping", "intra_abdominal_pressure", "valsalva", "explosive", "contact_risk", "hanging_grip"],
    intensityCap: "very_light",
    sessionMinutes: { min: 5, target: 20, max: 35 },
    weeklyMinutesTarget: 100,
    progressionRate: 0.03,
    energyBalance: "maintenance",
    proteinGPerKg: 1.7,
    keyMetrics: ["pain_score", "range_of_motion", "active_minutes", "energy", "adherence"],
    nonNegotiables: [
      "Do not exceed your surgeon's restrictions — they override everything here",
      "Walk short distances often to reduce clot risk",
      "Breathing exercises daily after chest or abdominal surgery",
      "Protein and sleep drive healing",
    ],
    cautions: [
      "Wound redness, discharge, fever, calf pain or swelling, or sudden breathlessness — seek care immediately",
      "No lifting beyond your prescribed limit, even if you feel fine",
    ],
    successSignals: ["Range returning", "Walking distance increasing", "Less pain medication needed"],
    expectedTimeline: "Follow your surgical protocol; typically 6-12 weeks to base activity",
  },
  long_covid: {
    id: "long_covid",
    label: "Post-viral recovery",
    purpose: "Rebuild after COVID or another viral illness without relapsing.",
    family: "recovery_rehab",
    mechanism:
      "Post-viral recovery is paced, not pushed. Where post-exertional symptom worsening exists, standard progressive training makes people worse — so activity is kept under the symptom threshold and expanded only when the previous level causes no next-day payback.",
    bucketWeights: { active_recovery: 8, mindbody_calm: 7, mobility_flexibility: 6, cardio_steady: 4, strength: 3 },
    primaryCategories: ["breathwork", "walking", "mobility", "yoga", "recovery", "rehab"],
    avoidTags: ["max_heart_rate", "vigorous_intensity", "long_duration", "heat_exposure", "explosive"],
    intensityCap: "very_light",
    sessionMinutes: { min: 5, target: 15, max: 30 },
    weeklyMinutesTarget: 80,
    progressionRate: 0.02,
    energyBalance: "maintenance",
    proteinGPerKg: 1.5,
    keyMetrics: ["energy", "rpe", "resting_hr", "sleep_quality", "mood", "adherence"],
    nonNegotiables: [
      "Stay below the effort level that causes next-day symptoms",
      "Very short bouts with full rest between",
      "Hold a level for a full week before adding anything",
      "Breathing retraining daily",
    ],
    cautions: [
      "Post-exertional malaise means reduce, not push through",
      "Chest pain, palpitations or fainting on exertion needs cardiac assessment before continuing",
      "Get medical clearance before resuming structured exercise",
    ],
    successSignals: ["No next-day crash", "Slowly increasing tolerance"],
    expectedTimeline: "Months, with fluctuation — that is expected",
  },
  cancer_recovery: {
    id: "cancer_recovery",
    label: "Exercise during/after cancer treatment",
    purpose: "Maintain strength, function and quality of life through treatment and recovery.",
    family: "recovery_rehab",
    mechanism:
      "Exercise during and after cancer treatment reduces fatigue, preserves muscle and improves quality of life and outcomes. Volume flexes with treatment cycles: lighter on treatment days, more on good days.",
    bucketWeights: { strength: 7, cardio_steady: 6, mobility_flexibility: 6, mindbody_calm: 6, active_recovery: 5 },
    primaryCategories: ["walking", "gym_strength", "yoga", "mobility", "breathwork", "swimming"],
    avoidTags: ["contact_risk", "heat_exposure", "max_heart_rate", "high_impact"],
    intensityCap: "light",
    sessionMinutes: { min: 5, target: 20, max: 40 },
    weeklyMinutesTarget: 120,
    progressionRate: 0.03,
    energyBalance: "maintenance",
    proteinGPerKg: 1.6,
    keyMetrics: ["energy", "active_minutes", "mood", "weight", "adherence", "pain_score"],
    nonNegotiables: [
      "Clear your plan with your oncology team",
      "Move a little every day, even 5 minutes on hard days",
      "Prioritise resistance work to preserve muscle",
      "Avoid crowded gyms when immune counts are low",
    ],
    cautions: [
      "Skip exercise with fever, very low blood counts, uncontrolled nausea or new bone pain",
      "Avoid swimming pools with a central line or during neutropenia",
      "Lymphoedema risk: progress upper-body load slowly under guidance",
    ],
    successSignals: ["Less treatment-related fatigue", "Holding on to strength and weight"],
    expectedTimeline: "Ongoing through treatment; rebuild over 6-12 months after",
  },
  migraine_relief: {
    id: "migraine_relief",
    label: "Fewer migraines",
    purpose: "Reduce migraine frequency and intensity.",
    family: "recovery_rehab",
    mechanism:
      "Regular moderate aerobic exercise reduces migraine frequency about as much as some preventive medication. Consistency, hydration, sleep regularity and neck/shoulder work matter; sudden maximal effort can itself trigger an attack.",
    bucketWeights: { cardio_steady: 8, mindbody_calm: 7, mobility_flexibility: 6, rehab_corrective: 5, strength: 4 },
    primaryCategories: ["walking", "yoga", "breathwork", "cycling", "swimming", "mobility"],
    avoidTags: ["max_heart_rate", "explosive", "inversion", "heat_exposure", "breath_retention", "vigorous_intensity"],
    intensityCap: "moderate",
    sessionMinutes: { min: 15, target: 30, max: 45 },
    weeklyMinutesTarget: 150,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["mood", "sleep_quality", "stress", "active_minutes", "pain_score", "adherence"],
    nonNegotiables: [
      "Same schedule daily — irregularity is a trigger",
      "Long warm-ups; never start hard",
      "Hydrate and do not skip meals before sessions",
      "Neck and shoulder mobility daily",
    ],
    cautions: ["Skip the session during an attack; resume gently after", "A sudden severe new headache needs urgent medical assessment"],
    successSignals: ["Fewer migraine days per month", "Shorter attacks"],
    expectedTimeline: "8-12 weeks",
  },
  digestive_health: {
    id: "digestive_health",
    label: "Better digestion",
    purpose: "Improve gut motility, bloating and regularity.",
    family: "recovery_rehab",
    mechanism:
      "Walking and gentle twisting movement speed gastric emptying and colonic transit; diaphragmatic breathing shifts the gut-brain axis toward rest-and-digest. High-intensity work on a full stomach does the opposite.",
    bucketWeights: { cardio_steady: 7, mindbody_calm: 7, mobility_flexibility: 6, strength: 4, active_recovery: 4 },
    primaryCategories: ["walking", "yoga", "breathwork", "mobility", "cycling"],
    avoidTags: ["intra_abdominal_pressure", "max_heart_rate", "inversion"],
    intensityCap: "moderate",
    sessionMinutes: { min: 10, target: 30, max: 45 },
    weeklyMinutesTarget: 160,
    progressionRate: 0.05,
    energyBalance: "maintenance",
    proteinGPerKg: 1.4,
    keyMetrics: ["energy", "stress", "sleep_quality", "steps", "adherence"],
    nonNegotiables: ["Walk 10-15 minutes after meals", "Diaphragmatic breathing before eating", "Do not train hard within 90 minutes of a big meal"],
    cautions: ["Blood in stool, unexplained weight loss or severe pain needs medical assessment, not exercise", "With reflux, avoid inversions and bending after meals"],
    successSignals: ["More regular bowel habit", "Less bloating"],
    expectedTimeline: "2-4 weeks",
  },
};

export const GOAL_LIST: GoalDefinition[] = Object.values(GOALS);

export const GOAL_FAMILY_LABELS: Record<string, string> = {
  body_composition: "Weight & body composition",
  musculoskeletal: "Joints, bones & pain",
  metabolic: "Metabolic & hormonal health",
  cardio_respiratory: "Heart, lungs & stamina",
  mental_wellbeing: "Mind, mood & sleep",
  life_stage: "Life stage",
  performance: "Performance & sport",
  recovery_rehab: "Recovery & rehabilitation",
  longevity: "Longevity",
};

export function getGoal(id: GoalId): GoalDefinition {
  return GOALS[id];
}

export function goalsByFamily(): { family: string; label: string; goals: GoalDefinition[] }[] {
  const families = new Map<string, GoalDefinition[]>();
  for (const goal of GOAL_LIST) {
    const list = families.get(goal.family) ?? [];
    list.push(goal);
    families.set(goal.family, list);
  }
  return [...families.entries()].map(([family, goals]) => ({
    family,
    label: GOAL_FAMILY_LABELS[family] ?? family,
    goals,
  }));
}
