/**
 * Blank profile factory and demo profiles.
 *
 * The demos exist so the planner can be exercised end to end without typing a
 * full intake, and they deliberately cover very different constraint sets:
 * joint pain in an older adult, weight loss with PCOS, back pain at a desk,
 * and a post-cardiac-event case that requires clearance.
 */

import { emptyScreen } from "./screening";
import type { FitnessProfile } from "./types";

export function createBlankProfile(id?: string): FitnessProfile {
  const now = new Date().toISOString();
  return {
    id: id ?? `fitprof_${Date.now().toString(36)}`,
    name: "",
    createdAt: now,
    updatedAt: now,
    age: 30,
    sex: "other",
    heightCm: 170,
    weightKg: 70,
    ethnicity: "south_asian",
    goals: [],
    primaryGoal: "maintain_weight",
    activityLevel: "sedentary",
    experience: "beginner",
    canWalk30MinUnaided: true,
    canGetUpFromFloorUnaided: true,
    conditions: [],
    medications: [],
    painPoints: [],
    injuries: [],
    screen: emptyScreen(),
    environmentPreference: "both",
    availableEquipment: ["none"],
    daysPerWeek: 4,
    minutesPerSession: 40,
    preferredTime: "morning",
    likedCategories: [],
    dislikedCategories: [],
    spaceConstraint: "room",
    climate: "temperate",
    sleepHours: 7,
    stressLevel: "moderate",
    language: "en",
  };
}

export const DEMO_PROFILES: FitnessProfile[] = [
  {
    ...createBlankProfile("fitprof_demo_arthritis"),
    name: "Sunita (demo) — knee arthritis",
    age: 58,
    sex: "female",
    heightCm: 158,
    weightKg: 74,
    waistCm: 92,
    ethnicity: "south_asian",
    primaryGoal: "arthritis",
    goals: ["arthritis", "joint_pain", "weight_loss", "balance_fall_prevention"],
    motivation: "I want to climb stairs without my knees hurting.",
    targetWeightKg: 66,
    activityLevel: "sedentary",
    experience: "beginner",
    restingHr: 78,
    systolicBp: 138,
    diastolicBp: 86,
    conditions: ["osteoarthritis_knee", "hypertension", "menopause"],
    medications: ["ace_inhibitor", "nsaid"],
    painPoints: [{ region: "knee", severity: 6, chronic: true, triggers: "Stairs and standing for long periods" }],
    injuries: [],
    canWalk30MinUnaided: true,
    canGetUpFromFloorUnaided: false,
    screen: { ...emptyScreen(), boneJointProblemWorsenedByExercise: true, medicationForHeartOrBloodPressure: true },
    environmentPreference: "both",
    availableEquipment: ["none", "chair", "resistance_band", "mat"],
    daysPerWeek: 5,
    minutesPerSession: 30,
    preferredTime: "morning",
    likedCategories: ["walking", "yoga", "swimming"],
    dislikedCategories: ["hiit", "running"],
    spaceConstraint: "room",
    climate: "hot_humid",
    sleepHours: 6,
    stressLevel: "moderate",
    dietPattern: "veg",
  },
  {
    ...createBlankProfile("fitprof_demo_pcos"),
    name: "Ritika (demo) — weight loss + PCOS",
    age: 34,
    sex: "female",
    heightCm: 163,
    weightKg: 78,
    waistCm: 94,
    ethnicity: "south_asian",
    primaryGoal: "weight_loss",
    goals: ["weight_loss", "pcos_hormonal", "belly_fat", "stress_calm", "sleep_quality"],
    motivation: "Regular cycles and more energy through the workday.",
    targetWeightKg: 66,
    activityLevel: "light",
    experience: "beginner",
    restingHr: 74,
    currentWeeklyMinutes: 90,
    conditions: ["pcos", "prediabetes", "insomnia"],
    medications: ["metformin"],
    painPoints: [{ region: "lower_back", severity: 3, chronic: false, triggers: "Long hours at the desk" }],
    injuries: [],
    canWalk30MinUnaided: true,
    canGetUpFromFloorUnaided: true,
    screen: emptyScreen(),
    environmentPreference: "both",
    availableEquipment: ["none", "mat", "dumbbells", "resistance_band", "shoes_running"],
    daysPerWeek: 5,
    minutesPerSession: 45,
    preferredTime: "early_morning",
    likedCategories: ["gym_strength", "walking", "dance", "yoga"],
    dislikedCategories: [],
    spaceConstraint: "hall_or_garden",
    climate: "polluted_city",
    sleepHours: 6,
    stressLevel: "high",
    dietPattern: "eggetarian",
  },
  {
    ...createBlankProfile("fitprof_demo_backpain"),
    name: "Arjun (demo) — desk job & back pain",
    age: 31,
    sex: "male",
    heightCm: 176,
    weightKg: 84,
    waistCm: 96,
    ethnicity: "south_asian",
    primaryGoal: "back_pain",
    goals: ["back_pain", "desk_job_reset", "posture", "muscle_gain"],
    motivation: "Sitting for ten hours a day is wrecking my lower back.",
    activityLevel: "sedentary",
    experience: "intermediate",
    restingHr: 68,
    currentWeeklyMinutes: 60,
    conditions: ["chronic_low_back_pain", "gerd"],
    medications: [],
    painPoints: [
      { region: "lower_back", severity: 5, chronic: true, triggers: "Sitting, and driving over 30 minutes" },
      { region: "neck", severity: 4, chronic: true, triggers: "Laptop work without a stand" },
    ],
    injuries: [],
    canWalk30MinUnaided: true,
    canGetUpFromFloorUnaided: true,
    screen: { ...emptyScreen(), boneJointProblemWorsenedByExercise: true },
    environmentPreference: "both",
    availableEquipment: ["none", "mat", "resistance_band", "dumbbells", "foam_roller", "gym_access", "machines"],
    daysPerWeek: 4,
    minutesPerSession: 50,
    preferredTime: "evening",
    likedCategories: ["gym_strength", "walking", "sports"],
    dislikedCategories: ["dance"],
    spaceConstraint: "gym",
    climate: "temperate",
    sleepHours: 7,
    stressLevel: "high",
    dietPattern: "non_veg",
  },
  {
    ...createBlankProfile("fitprof_demo_cardiac"),
    name: "Mohan (demo) — post-cardiac, needs clearance",
    age: 66,
    sex: "male",
    heightCm: 170,
    weightKg: 80,
    waistCm: 104,
    ethnicity: "south_asian",
    primaryGoal: "heart_health",
    goals: ["heart_health", "blood_pressure", "weight_loss", "senior_functional"],
    motivation: "Walk to the market and back without stopping.",
    activityLevel: "sedentary",
    experience: "beginner",
    restingHr: 62,
    systolicBp: 142,
    diastolicBp: 88,
    conditions: ["coronary_artery_disease", "hypertension", "diabetes_type2"],
    medications: ["beta_blocker", "statin", "metformin", "ace_inhibitor"],
    painPoints: [{ region: "knee", severity: 3, chronic: true }],
    injuries: [],
    surgeries: ["Coronary angioplasty, 14 months ago"],
    canWalk30MinUnaided: false,
    canGetUpFromFloorUnaided: true,
    screen: { ...emptyScreen(), diagnosedHeartCondition: true, medicationForHeartOrBloodPressure: true },
    hasMedicalClearance: true,
    environmentPreference: "both",
    availableEquipment: ["none", "chair", "resistance_band", "stationary_bike"],
    daysPerWeek: 6,
    minutesPerSession: 25,
    preferredTime: "morning",
    likedCategories: ["walking", "breathwork", "yoga"],
    dislikedCategories: ["hiit", "sports"],
    spaceConstraint: "room",
    climate: "hot_dry",
    sleepHours: 7,
    stressLevel: "moderate",
    dietPattern: "veg",
    smoker: false,
  },
];
